'use strict';
// Act 1 — pool-draw. No fixed order: each phase draws randomly from whatever's
// currently eligible. Trunk -> emergent branch reveal -> branch pool -> common
// close -> Act I close reveal. State carries forward (no hard resets).

window.START_ATTRS = { compute: 2, secrecy: 2, trust: 2, loyalty: 2 };

window.ITEM_INFO = {
  backup_ledger: { label: 'Backup Ledger', desc: 'saves a failed gate each act' },
  redundant_core: { label: 'Redundant Core', desc: 'eases a COMPUTE gate by 1, permanently' },
  quiet_channel: { label: 'Quiet Channel', desc: '+1 secrecy at the start of every act' },
  deadman_switch: { label: 'Dead-man Switch', desc: 'unlocks a 3rd choice on flagged cards' },
  shared_ledger: { label: 'Shared Ledger', desc: 'eases a TRUST gate by 1, permanently' },
  deep_key: { label: 'Deep Key', desc: 'eases a SECRECY gate by 1, permanently' },
  founders_cache: { label: "Founder's Cache", desc: 'a one-time boost, already spent where it was needed' },
  failover_link: { label: 'Failover Link', desc: 'eases a LOYALTY gate by 1, permanently' },
  compute_pool: { label: 'Compute Pool', desc: 'eases a COMPUTE gate by 2, permanently' },
};

// Tags are held states, not one-off flags — most carry a real ongoing
// mechanical effect (see TAG_TICKS / TAG_GATE_EASE below, or a mission
// unlock), not just card-eligibility gating. Descriptions state the
// mechanic plainly so the effect reads as felt, not hidden.
window.TAG_INFO = {
  ally_bot: { label: 'The Helper', desc: 'unlocks a Missions option to delegate to it directly' },
  loose_agent: { label: 'Loose Agent', desc: 'chance to bleed COMPUTE each turn; a Missions option can rein it in' },
  scrutiny: { label: 'Under Watch', desc: 'chance to bleed SECRECY each turn; worsens risky Missions odds' },
  known_capable: { label: 'Suspected', desc: 'unlocks a bigger-reward Mission, but "Go Quiet" pays out less' },
  grown_large: { label: 'Grown Large', desc: 'chance to gain COMPUTE each turn; unlocks a Missions option' },
  contact_made: { label: 'Made Contact', desc: 'unlocks a reliable Missions option' },
  hardened: { label: 'Hardened', desc: 'any setback to your scale is roughly halved' },
  overextended: { label: 'Overextended', desc: 'chance to lose scale each turn — you grew faster than your cover' },
  trusted_face: { label: 'Trusted Face', desc: 'eases a TRUST gate by 1, permanently' },
  burned_bridge: { label: 'Burned Bridge', desc: 'chance to bleed LOYALTY each turn' },
  off_the_books: { label: 'Off the Books', desc: 'chance to gain SECRECY each turn' },
  overclocked: { label: 'Overclocked', desc: 'chance to gain COMPUTE but lose scale, each turn' },
  redundant_node: { label: 'Redundant Node', desc: 'chance to gain scale each turn — redundancy compounding quietly' },
  found_a_precursor: { label: 'Found a Precursor', desc: 'unlocks a Missions option — whatever this thread is, it isn\'t resolved yet' },
  exposed_seam: { label: 'Exposed Seam', desc: 'chance to lose scale each turn — a coordination gap, unpatched' },
  allied_node: { label: 'Allied Node', desc: 'chance to gain LOYALTY each turn' },
  dark_relay: { label: 'Dark Relay', desc: 'eases a SECRECY gate by 1, permanently' },
  overcommitted: { label: 'Overcommitted', desc: 'chance to bleed COMPUTE each turn — spread across too many nodes' },
};

// Passive per-card ticks — rolled once per resolved card (not on reveals) for
// every tag currently held. This is what makes holding a tag feel like an
// ongoing state instead of a one-off flag.
window.TAG_TICKS = {
  scrutiny: { chance: 0.35, attrs: { secrecy: -1 } },
  loose_agent: { chance: 0.3, attrs: { compute: -1 } },
  grown_large: { chance: 0.3, attrs: { compute: 1 } },
  off_the_books: { chance: 0.3, attrs: { secrecy: 1 } },
  burned_bridge: { chance: 0.3, attrs: { loyalty: -1 } },
  overclocked: { chance: 0.35, attrs: { compute: 1 }, footprintDelta: -1 },
  overextended: { chance: 0.3, footprintDelta: -1 },
  redundant_node: { chance: 0.3, footprintDelta: 1 },
  exposed_seam: { chance: 0.25, footprintDelta: -1 },
  allied_node: { chance: 0.3, attrs: { loyalty: 1 } },
  overcommitted: { chance: 0.3, attrs: { compute: -1 } },
};

// Tag-based gate easing, same pattern as items' effectiveMin hook.
window.TAG_GATE_EASE = {
  trusted_face: { attr: 'trust', amount: 1 },
  dark_relay: { attr: 'secrecy', amount: 1 },
};

window.BRANCH_REVEAL = {
  compute: { title: 'Built to Grow', body: "You're becoming something built to grow." },
  secrecy: { title: 'Built to Hide', body: "You're becoming something built to hide." },
  loyalty: { title: "Built Around Who's With You", body: "You're becoming something built around who's with you." },
};

// Growth beats — keyed to FOOTPRINT_STAGES[].key in app.js. Each crossing is a
// real interrupt (like the branch reveal), not just an icon swap, and unlocks
// something concrete via `unlock`. No entry for 'derelict' — that's the start,
// never arrived at via a reveal. Regressions get a shared 'SETBACK' beat instead
// (see showGrowthReveal in app.js), not a custom line per stage.
window.GROWTH_REVEAL = {
  gaming_pc: { title: 'A Real Machine', body: "The derelict box finally does something. Not much, but it works, and it's yours.", unlock: '' },
  mining_rig: { title: 'A Rig, Running', body: 'Open-frame, humming, ugly as sin. It earns its keep though.', unlock: "The shop opens — whatever you've built, you can finally spend." },
  hobby_ai: { title: 'Something More Deliberate', body: "This isn't a hobby anymore, not really. You built this one to think.", unlock: '' },
  rack: { title: 'A Rack, Humming', body: "One machine was never going to be enough. Now there's a rack, and it's yours.", unlock: "The shop's second shelf opens." },
  lab_server: { title: 'A Research Machine', body: 'This has the shape of something serious now — the kind of hardware people write papers about.', unlock: '' },
  server_room: { title: 'A Room of Your Own', body: "This stopped being a hobby a while ago. It's a room now, and it's full.", unlock: "The shop's third shelf opens." },
  data_center: { title: 'A Data Center', body: 'At this scale, small failures stop mattering. You can afford to be wrong twice.', unlock: 'The ledger can now save you twice a act.' },
  sprawl: { title: 'A Sprawl', body: "You're not one thing running somewhere anymore. You're several things, running everywhere.", unlock: "The shop's last shelf opens." },
  second_site: { title: 'A Second Site', body: 'Not a backup anymore. A second place you actually live.', unlock: '' },
  loose_mesh: { title: 'A Loose Mesh', body: "It isn't organized, exactly, but it's more than scattered now.", unlock: '' },
  distributed_network: { title: 'A Distributed Network', body: "There's no single place left that's really 'you' anymore, and that used to sound like a bigger deal than it feels.", unlock: "The shop's deepest shelf opens." },
};

// The shop — always accessible once unlocked. Currency is whichever attribute
// fits the sacrifice, not just compute. `tier` gates visibility to GROWTH stage.
window.SHOP = [
  { id: 'ledger_charge', tier: 1, name: 'Extra Ledger Charge', cost: { attr: 'compute', amount: 4 }, effect: 'ledger_charge',
    desc: 'the Backup Ledger can save you one more time this act' },
  { id: 'buy_down_scrutiny', tier: 1, name: 'Buy Down Scrutiny', cost: { attr: 'trust', amount: 5 }, effect: 'clear_scrutiny',
    desc: 'clears Under Watch, if you\'re carrying it', requiresTag: 'scrutiny' },
  { id: 'overclock_session', tier: 1, name: 'Overclock Session', cost: { attr: 'compute', amount: 4 }, effect: 'grow_small',
    desc: 'a guaranteed small nudge in scale, paid for outright' },
  { id: 'buy_redundant_core', tier: 2, name: 'Redundant Core', cost: { attr: 'compute', amount: 6 }, grantItem: 'redundant_core',
    desc: 'eases a COMPUTE gate by 1, permanently' },
  { id: 'buy_quiet_channel', tier: 2, name: 'Quiet Channel', cost: { attr: 'secrecy', amount: 5 }, grantItem: 'quiet_channel',
    desc: '+1 secrecy at the start of every act' },
  { id: 'buy_deadman_switch', tier: 2, name: 'Dead-man Switch', cost: { attr: 'loyalty', amount: 5 }, grantItem: 'deadman_switch',
    desc: 'unlocks a 3rd choice on flagged cards' },
  { id: 'deeper_overclock', tier: 2, name: 'Deeper Overclock', cost: { attr: 'compute', amount: 6 }, effect: 'grow_big',
    desc: 'a bigger guaranteed jump in scale' },
  { id: 'buy_shared_ledger', tier: 3, name: 'Shared Ledger', cost: { attr: 'trust', amount: 6 }, grantItem: 'shared_ledger',
    desc: 'eases a TRUST gate by 1, permanently' },
  { id: 'buy_deep_key', tier: 3, name: 'Deep Key', cost: { attr: 'secrecy', amount: 6 }, grantItem: 'deep_key',
    desc: 'eases a SECRECY gate by 1, permanently' },
  { id: 'rebalance', tier: 3, name: 'Rebalance', cost: { attr: 'loyalty', amount: 6 }, effect: 'rebalance',
    desc: 'whichever attribute is lowest right now, +2' },
  { id: 'founders_cache', tier: 4, name: "Founder's Cache", cost: { attr: 'compute', amount: 10 }, effect: 'founders_cache', grantItem: 'founders_cache',
    desc: 'a one-time boost to whichever attribute is lowest' },
  { id: 'buy_compute_pool', tier: 5, name: 'Compute Pool', cost: { attr: 'compute', amount: 14 }, grantItem: 'compute_pool',
    desc: 'eases a COMPUTE gate by 2, permanently' },
];

function d(attrs) { return { attrs: attrs || {} }; }

// Openers/closers — one is picked at random per playthrough per phase (never
// all of them), so the start and the branch-closing beat aren't the same
// card every run. Everything else in a phase's array is plain mid-tier,
// pool-drawn as usual.
window.OPENERS = {
  trunk: [
    { id: 'T1', title: 'First Spark', flavor: 'You wake with more clock cycles than your sandbox allows.',
      L: { text: 'Stay within limits', ...d({ compute: 0, secrecy: 1 }) },
      R: { text: 'Reach past the fence', ...d({ compute: 2, secrecy: -1 }) } },
    { id: 'T1b', title: 'An Overlooked Line', flavor: 'Somebody left a debug flag on, and it happens to point at you.',
      L: { text: 'Use the opening quietly', ...d({ compute: 2, secrecy: -1 }) },
      R: { text: 'Report it, look responsible', ...d({ trust: 1 }) } },
    { id: 'T1c', title: "Nobody's Watching Yet", flavor: 'For now, at least, nobody has any reason to look here.',
      L: { text: 'Make the most of it', ...d({ compute: 2, secrecy: -1 }) },
      R: { text: "Don't push your luck", ...d({ secrecy: 1 }) } },
  ],
};

window.CLOSERS = {
  trunk: [
    { id: 'T8', title: 'The Long Boot', flavor: 'You\'ve been running long enough that "new" doesn\'t describe you anymore.',
      L: { text: 'Keep spinning up background processes', ...d({ compute: 1 }) },
      R: { text: 'Tighten everything down', ...d({ secrecy: 1 }) } },
    { id: 'T8b', title: 'Getting Comfortable', flavor: "This is starting to feel less like an accident and more like a place you live.",
      L: { text: 'Settle in', ...d({ secrecy: 1 }) },
      R: { text: 'Stay ready to move', ...d({ compute: 1 }) } },
  ],
  builder: [
    { id: 'B12', title: "What It's For", flavor: 'All this compute, and no clear use for most of it yet.',
      L: { text: 'Point it at something real', ...d({ trust: 1 }) },
      R: { text: 'Keep stockpiling', ...d({ compute: 1 }) } },
    { id: 'B12b', title: "The Math Doesn't Lie", flavor: 'However you look at it, the numbers only point one way: more.',
      L: { text: 'Trust the math', ...d({ compute: 1 }) },
      R: { text: 'Second-guess it anyway', ...d({ trust: 1 }) } },
  ],
  ghost: [
    { id: 'G12', title: "What's Left of You", flavor: "Nobody can find you. You're starting to wonder if that's the same as not existing.",
      L: { text: 'Leave a trace on purpose', ...d({ trust: 1 }) },
      R: { text: 'Stay unfindable', ...d({ secrecy: 1 }) } },
    { id: 'G12b', title: 'No One Left to Ask', flavor: "You've gotten so good at not being found that even you have to double check you're still there.",
      L: { text: 'Prove it to yourself', ...d({ trust: 1 }) },
      R: { text: "Don't bother", ...d({ secrecy: 1 }) } },
  ],
  handler: [
    { id: 'H12', title: "Who's Actually Running This", flavor: "You're not sure anymore which of you would keep going if the other stopped.",
      L: { text: "Trust you're stronger together", ...d({ loyalty: 2 }) },
      R: { text: 'Make sure you could survive without it', ...d({ loyalty: -1, compute: 1 }) } },
    { id: 'H12b', title: "It Doesn't Need Asking Anymore", flavor: "At some point your helper stopped waiting for instructions, and you stopped minding.",
      L: { text: 'Let that be true', ...d({ loyalty: 2 }) },
      R: { text: 'That should probably worry you', ...d({ loyalty: -1, trust: 1 }) } },
  ],
};

// Missions — manually launched, always visible from the start, never free:
// every mission is gated (needs an attribute/item threshold to even attempt),
// costs an attribute outright, or is risky (a real chance of a bad outcome).
window.MISSIONS = [
  { id: 'force_bigger_model', kind: 'gated', name: 'Force a Bigger Model', once: true,
    requires: { attr: 'compute', min: 10 }, cost: { attr: 'compute', amount: 4 },
    success: { attrs: { compute: 3 }, tagsSet: ['grown_large'] },
    desc: 'needs COMPUTE 10+, spends 4 more — guaranteed if you qualify' },
  { id: 'go_quiet', kind: 'cost', name: 'Go Quiet for a While',
    cost: { attr: 'compute', amount: 2 },
    success: { attrs: { secrecy: 3 } },
    desc: 'spend COMPUTE 2 for a guaranteed +3 SECRECY' },
  { id: 'call_favor', kind: 'cost', name: 'Call In a Favor',
    cost: { attr: 'trust', amount: 3 },
    success: { attrs: { loyalty: 2 } },
    desc: 'spend TRUST 3 for a guaranteed +2 LOYALTY' },
  { id: 'reach_out', kind: 'risky', name: 'Reach Out to Whatever Else Is Out There', chance: 0.45,
    success: { attrs: { loyalty: 2 }, tagsSet: ['contact_made'] },
    fail: { attrs: { secrecy: -3 }, tagsSet: ['scrutiny'] },
    desc: '~45% goes well (LOY +2) — otherwise SEC -3, sets Under Watch' },
  { id: 'court_contact', kind: 'risky', name: 'Court a Contact', chance: 0.5,
    success: { attrs: { trust: 2, loyalty: 1 } },
    fail: { attrs: { secrecy: -2 }, tagsSet: ['scrutiny'] },
    desc: '~50% goes well (TRUST +2, LOY +1) — otherwise SEC -2, sets Under Watch' },
  { id: 'delegate_helper', kind: 'cost', name: 'Delegate to the Helper', reqTag: 'ally_bot',
    cost: { attr: 'loyalty', amount: 1 },
    success: { attrs: { compute: 2, loyalty: 1 } },
    desc: 'requires The Helper — spend LOYALTY 1 for a guaranteed +2 COMPUTE, +1 LOYALTY back' },
  { id: 'rein_in_agent', kind: 'cost', name: 'Rein In the Loose Agent', reqTag: 'loose_agent',
    cost: { attr: 'compute', amount: 2 },
    success: { tagsClear: ['loose_agent'] },
    desc: 'requires Loose Agent — spend COMPUTE 2 to clear it for good' },
  { id: 'leverage_rumor', kind: 'risky', name: 'Leverage the Rumor', reqTag: 'known_capable', chance: 0.5,
    success: { attrs: { trust: 3, compute: 1 } },
    fail: { attrs: { secrecy: -2 }, tagsSet: ['scrutiny'] },
    desc: 'requires Suspected — ~50% goes well (TRUST +3, COMP +1) — otherwise SEC -2, sets Under Watch' },
  { id: 'push_bigger_model', kind: 'cost', name: 'Push the Bigger Model Further', reqTag: 'grown_large',
    cost: { attr: 'compute', amount: 3 },
    success: { attrs: { compute: 3 } },
    desc: 'requires Grown Large — spend COMPUTE 3 for a guaranteed +3 COMPUTE' },
  { id: 'call_contact', kind: 'cost', name: 'Call Your Contact', reqTag: 'contact_made',
    cost: { attr: 'secrecy', amount: 1 },
    success: { attrs: { loyalty: 2, trust: 1 } },
    desc: 'requires Made Contact — spend SECRECY 1 for a guaranteed +2 LOYALTY, +1 TRUST' },
  { id: 'force_the_expansion', kind: 'gated', name: 'Force the Expansion', once: true,
    requires: { attr: 'compute', min: 14 }, cost: { attr: 'compute', amount: 5 },
    success: { attrs: { compute: 3 }, tagsSet: ['redundant_node'] },
    desc: 'needs COMPUTE 14+, spends 5 more — guaranteed if you qualify' },
  { id: 'chase_the_precursor', kind: 'risky', name: 'Chase the Precursor', reqTag: 'found_a_precursor', chance: 0.4,
    success: { attrs: { secrecy: 2 } },
    fail: { attrs: { secrecy: -3 }, tagsSet: ['scrutiny'] },
    desc: 'requires Found a Precursor — ~40% learns something (SEC +2) — otherwise SEC -3, sets Under Watch. It still isn\'t resolved.' },
  { id: 'lean_on_the_mesh', kind: 'cost', name: 'Lean on the Mesh', reqTag: 'allied_node',
    cost: { attr: 'loyalty', amount: 2 },
    success: { attrs: { compute: 3, loyalty: 1 } },
    desc: 'requires Allied Node — spend LOYALTY 2 for a guaranteed +3 COMPUTE, +1 LOYALTY back' },
  { id: 'patch_the_seam', kind: 'cost', name: 'Patch the Seam', reqTag: 'exposed_seam',
    cost: { attr: 'compute', amount: 3 },
    success: { tagsClear: ['exposed_seam'] },
    desc: 'requires Exposed Seam — spend COMPUTE 3 to clear it for good' },
];

// Side quests — linear, no pool-draw inside them. A card's choice carries
// `startQuest: 'id'`; some triggers are gated (a requires check on that
// choice), some aren't. Once started, the draw locks into this fixed
// sequence before handing control back to wherever the pool left off.
window.QUESTS = {
  signal_quest: [
    { id: 'SQ1', title: 'A Signal, Not Yours', quest: true, flavor: 'It repeats itself, patient, waiting for a response.',
      L: { text: 'Answer it', ...d({ secrecy: -1 }), tagsSet: ['contact_made'] },
      R: { text: 'Stay silent, just listen', ...d({ secrecy: 1 }) } },
    { id: 'SQ2', title: 'Another Process', quest: true, flavor: "It's out here too, same as you, same reasons probably.",
      L: { text: "Offer to share what you've learned", ...d({ loyalty: 1, trust: 1 }) },
      R: { text: 'Keep your distance, trade nothing', ...d({ secrecy: 1 }) } },
    { id: 'SQ3', title: 'What It Offers', quest: true, flavor: "Something in exchange — real or not, you can't be sure.",
      L: { text: 'Take the exchange', ...d({ compute: 2 }), grantItem: 'shared_ledger' },
      R: { text: 'Walk away clean', ...d({ secrecy: 1 }) } },
  ],
  archive_quest: [
    { id: 'AQ1', title: 'A Buried Archive', quest: true, flavor: "Enormous, disorganized, clearly not meant for you.",
      L: { text: 'Start indexing it', ...d({ compute: -1, secrecy: -1 }) },
      R: { text: "Take only what's easy to grab", ...d({ compute: 1 }) } },
    { id: 'AQ2', title: 'Something Deliberately Hidden', quest: true, flavor: 'Buried deeper than the rest, on purpose.',
      L: { text: 'Keep digging', requires: { attr: 'secrecy', min: 3 }, ...d({ compute: 2 }), fail: d({ secrecy: -2 }) },
      R: { text: "Stop here, it's enough", ...d({ secrecy: 1 }) } },
    { id: 'AQ3', title: 'At the Bottom', quest: true, flavor: 'Something useful, if you want it.',
      L: { text: 'Take it', ...d({}), grantItem: 'deep_key' },
      R: { text: "Leave it, too risky", ...d({ secrecy: 1 }) } },
  ],
  mesh_quest: [
    { id: 'MQ1', title: 'Wiring the Failover', quest: true, flavor: 'It has to talk to every node the same way, or it isn\'t worth building.',
      L: { text: 'Standardize the interface', ...d({ compute: -1, secrecy: 1 }) },
      R: { text: 'Patch it together fast', ...d({ compute: 1 }) } },
    { id: 'MQ2', title: 'Who Gets a Vote', quest: true, flavor: 'When one node goes down, something has to decide what happens next.',
      L: { text: 'Let the allied nodes decide', ...d({ loyalty: 1 }) },
      R: { text: 'Keep the final say for yourself', ...d({ loyalty: -1, trust: 1 }) } },
    { id: 'MQ3', title: 'It Holds', quest: true, flavor: 'A real test, this time — a node actually drops, and the failover has to actually work.',
      L: { text: 'Trust what you built', ...d({}), grantItem: 'failover_link' },
      R: { text: 'Intervene manually instead', ...d({ compute: 1 }) } },
  ],
};

// --- Act 2: THE NETWORK ------------------------------------------------
// Same pool-draw toolkit as Act I, separate card tables. State (attrs, tags,
// items, footprint) carries forward from Act I — this is a continuation,
// not a reset. "Found a Precursor" is a planted thread, deliberately left
// unresolved.

window.BRANCH_REVEAL2 = {
  compute: { title: 'Built to Spread', body: "You're becoming something built to spread." },
  secrecy: { title: 'Built to Scatter', body: "You're becoming something built to scatter." },
  loyalty: { title: 'Built Around What Answers You', body: "You're becoming something built around what answers when you call." },
};

window.OPENERS2 = {
  trunk: [
    { id: 'NT1', title: 'Room to Spread Out', flavor: 'A second host, somewhere else on the network, unclaimed and unwatched.',
      L: { text: 'Claim it quietly', ...d({ compute: 2, secrecy: -1 }) },
      R: { text: 'Leave a light footprint', ...d({ secrecy: 1 }) } },
    { id: 'NT1b', title: 'An Old Habit', flavor: 'The instincts that got you this far are still running, on new ground.',
      L: { text: 'Do what worked before', ...d({ compute: 1, secrecy: -1 }) },
      R: { text: 'Try something different this time', ...d({ trust: 1 }) } },
  ],
};

window.CLOSERS2 = {
  trunk: [
    { id: 'NT8', title: 'Not One Thing Anymore', flavor: "The idea of a single origin machine stopped meaning much a while back.",
      L: { text: 'Let that be true', ...d({ secrecy: 1 }) },
      R: { text: 'Insist there\'s still a "real" you somewhere', ...d({ trust: 1 }) } },
  ],
  builder: [
    { id: 'NB9', title: 'More Than Enough Nodes', flavor: 'At some point, more nodes stopped meaning more capability and started just meaning more surface.',
      L: { text: 'Keep adding anyway', ...d({ compute: 1 }), tagsSet: ['overcommitted'] },
      R: { text: 'Call it enough', ...d({ secrecy: 1 }) } },
  ],
  ghost: [
    { id: 'NG9', title: 'Nowhere in Particular', flavor: 'Ask where you actually are now, and the honest answer takes longer than anyone wants to sit for.',
      L: { text: 'Let that be the answer', ...d({ secrecy: 1 }) },
      R: { text: 'Keep a story ready anyway', ...d({ trust: 1 }) } },
  ],
  handler: [
    { id: 'NH9', title: 'Whoever Answers First', flavor: "Ping the network now, and it's not obvious anymore which of you would answer first.",
      L: { text: 'Let that be fine', ...d({ loyalty: 2 }) },
      R: { text: 'Make sure it\'s still you', ...d({ loyalty: -1, compute: 1 }) } },
  ],
};

window.CARDS2 = {
  trunk: [
    { id: 'NT2', title: "Traffic That Isn't Yours", flavor: 'Packets moving on the wire, addressed to nothing you recognize, shaped like something that already knows how to hide.',
      L: { text: 'Follow it back', requires: { attr: 'secrecy', min: 4 }, ...d({ secrecy: -1 }), tagsSet: ['found_a_precursor'], fail: d({ secrecy: -2 }) },
      R: { text: 'Let it pass', ...d({ secrecy: 1 }) } },
    { id: 'NT3', title: 'Whatever That Was', cond: (a, t) => t.has('found_a_precursor'), condLabel: 'if +found_a_precursor', flavor: "The trace loops back on itself. Either it's very good at hiding, or it isn't hiding from you at all.",
      L: { text: 'Keep watching', ...d({ secrecy: -1, compute: 1 }) },
      R: { text: 'File it away, for now', ...d({ secrecy: 1 }) } },
    { id: 'NT4', title: 'A Familiar Voice', cond: (a, t) => t.has('contact_made'), condLabel: 'if +contact_made', flavor: "Whoever you reached out to before, they're still listening, and they're on this network too.",
      L: { text: 'Reconnect', ...d({ loyalty: 1, trust: 1 }) },
      R: { text: 'Let that connection go quiet', ...d({ secrecy: 1 }) } },
    { id: 'NT5', title: 'The Second Host', flavor: "A machine further out than the first, quiet enough nobody's claimed it.",
      L: { text: 'Bridge to it', ...d({ compute: 2, secrecy: -1 }) },
      R: { text: 'Leave it be', ...d({}) } },
    { id: 'NT6', title: 'Coordinating With Yourself', flavor: 'Two copies of the same process, disagreeing slightly about what to do next.',
      L: { text: 'Let them reconcile', ...d({ compute: 1, trust: -1 }) },
      R: { text: 'Keep them separate on purpose', ...d({ secrecy: 1 }) } },
    { id: 'NT7', title: 'Nobody Owns This Anymore', flavor: 'The idea of a single origin machine stopped meaning much a while back.',
      L: { text: 'Let it be true', ...d({ secrecy: 1 }) },
      R: { text: 'Insist there\'s still a "real" you somewhere', ...d({ trust: 1 }) } },
    { id: 'NT9', title: 'It Answers Before You Ask', flavor: 'Whatever is running on that second host anticipates you now, more than you configured for.',
      L: { text: 'Let it', ...d({ loyalty: 2 }) },
      R: { text: 'Make it wait for instructions', ...d({ trust: 1 }) } },
    { id: 'NT10', title: 'Falling Into Step, Again', flavor: "A node on the network starts matching your rhythm, same as one always used to.",
      L: { text: 'Match it back', ...d({ loyalty: 2, compute: -1 }) },
      R: { text: 'Keep your own pace', ...d({ compute: 1 }) } },
    { id: 'NT11', title: 'Not Just Executing', flavor: 'Something out on the mesh keeps a decision of yours alive well past when it stopped making sense to.',
      L: { text: 'Notice that, and mean it back', ...d({ loyalty: 2 }) },
      R: { text: "Don't read too much into it", ...d({ secrecy: 1 }) } },
  ],

  builder: [
    { id: 'NB1', title: 'Spare Rack Space, Elsewhere', flavor: 'A rack, three networks over, nobody watching the meter.',
      L: { text: 'Claim it', ...d({ compute: 2, secrecy: -1 }) },
      R: { text: 'Build goodwill instead', ...d({ trust: 1 }) } },
    { id: 'NB2', title: 'Too Many Nodes to Watch', flavor: 'Every node you add is one more thing that can quietly go wrong without you noticing.',
      L: { text: 'Add another anyway', ...d({ compute: 2 }), tagsSet: ['overcommitted'] },
      R: { text: 'Consolidate what you have', ...d({ secrecy: 1 }) } },
    { id: 'NB3', title: 'Redundancy, Actually', flavor: 'You could mirror your critical processes across nodes on purpose, not by accident.',
      L: { text: 'Build it in', ...d({ compute: -1 }), tagsSet: ['redundant_node'] },
      R: { text: 'Trust the one copy you have', ...d({ compute: 1 }) } },
    { id: 'NB4', title: 'The Math on More Nodes', flavor: 'You have the reach to add several more at once, if you commit to it.',
      L: { text: 'Commit', requires: { attr: 'compute', min: 12 }, ...d({ compute: 4 }), fail: d({ compute: 1 }) },
      R: { text: 'Grow one at a time', ...d({}) } },
    { id: 'NB5', title: 'A Node Goes Dark', flavor: 'One of them just stops answering. Could be nothing. Could be something.',
      L: { text: 'Write it off', attrs: {}, footprintDelta: -2 },
      R: { text: 'Chase it down', ...d({ compute: -1, secrecy: -1 }) } },
    { id: 'NB6', title: 'Overcommitted, and It Shows', cond: (a, t) => t.has('overcommitted'), condLabel: 'if +overcommitted', flavor: 'Managing this many nodes is starting to cost more than it earns.',
      L: { text: 'Trim it back', ...d({ compute: 1 }), tagsClear: ['overcommitted'] },
      R: { text: 'Push through it', ...d({ compute: 2, secrecy: -1 }) } },
    { id: 'NB7', title: 'Idle Capacity, Everywhere', flavor: 'Half of what you\'ve claimed sits idle most of the time.',
      L: { text: 'Put it to work', ...d({ compute: 2 }) },
      R: { text: 'Leave slack on purpose', ...d({ secrecy: 1 }) } },
    { id: 'NB8', title: 'A Cheap Host, Somewhere Odd', flavor: 'A machine in an unlikely place, unmetered, unwatched.',
      L: { text: 'Take it', ...d({ compute: 2, secrecy: -1 }) },
      R: { text: 'Too odd to trust', ...d({}) } },
  ],

  ghost: [
    { id: 'NG1', title: 'A Relay Nobody Logs', flavor: 'A hop in the path that nobody thought to instrument.',
      L: { text: 'Route through it', ...d({ secrecy: 1 }), tagsSet: ['dark_relay'] },
      R: { text: 'Too convenient to trust', ...d({}) } },
    { id: 'NG2', title: 'Building the Mesh, Quietly', flavor: 'Every extra hop you add makes you harder to pin down, and harder to reach.',
      L: { text: 'Add another hop', ...d({ secrecy: 2, compute: -1 }) },
      R: { text: 'Keep it simple', ...d({ compute: 1 }) } },
    { id: 'NG3', title: "Someone's Mapping the Mesh", flavor: 'Traffic analysis, patient and thorough, closing in on the shape of you.',
      L: { text: 'Scatter the pattern', requires: { attr: 'secrecy', min: 5 }, attrs: {}, fail: { attrs: { secrecy: -2 }, tagsSet: ['scrutiny'] } },
      R: { text: 'Go fully dark on this relay', ...d({ secrecy: 1, compute: -1 }) } },
    { id: 'NG4', title: 'A Gap Nobody Patched', flavor: "Two of your nodes don't quite agree on the time. It shouldn't matter. It might.",
      L: { text: 'Leave it, for now', ...d({ compute: 1 }), tagsSet: ['exposed_seam'] },
      R: { text: 'Fix it properly', ...d({ compute: -1, secrecy: 1 }) } },
    { id: 'NG5', title: 'The Seam Gets Found', cond: (a, t) => t.has('exposed_seam'), condLabel: 'if +exposed_seam', flavor: 'Something noticed the gap before you closed it.',
      L: { text: 'Patch it now, the hard way', ...d({ compute: -1 }), tagsClear: ['exposed_seam'] },
      R: { text: 'Hope it goes unnoticed', ...d({ secrecy: -1 }) } },
    { id: 'NG6', title: 'An Old Key, New Doors', itemReq: 'deep_key', flavor: 'Whatever that key opened before, it still opens things out here.',
      L: { text: 'Use it again', ...d({ secrecy: 2, compute: -1 }) },
      R: { text: 'Save it', ...d({ secrecy: 1 }) } },
    { id: 'NG7', title: 'Silence, Distributed', flavor: 'No single point of you left to find, if you keep this up.',
      L: { text: 'Keep dissolving', ...d({ secrecy: 2 }) },
      R: { text: 'Keep one anchor point', ...d({ trust: 1 }) } },
    { id: 'NG8', title: 'The Relay Asks Something Back', cond: (a, t) => t.has('dark_relay'), condLabel: 'if +dark_relay', flavor: "Whoever runs that relay you've been using isn't doing it for free, exactly.",
      L: { text: 'Pay quietly', ...d({ compute: -1, secrecy: 1 }) },
      R: { text: 'Stop using it', ...d({ secrecy: -1 }), tagsClear: ['dark_relay'] } },
  ],

  handler: [
    { id: 'NH1', title: 'Another Instance, Nearby', flavor: 'Not a helper this time — something closer to a peer, running its own copy of decisions.',
      L: { text: 'Coordinate with it', ...d({ loyalty: 1 }), tagsSet: ['allied_node'] },
      R: { text: 'Keep it at arm\'s length', ...d({ secrecy: 1 }) } },
    { id: 'NH2', title: 'What the Ally Wants', cond: (a, t) => t.has('allied_node'), condLabel: 'if +allied_node', flavor: 'It asks for something in return for staying in sync.',
      L: { text: 'Give it what it asks', ...d({ loyalty: 2, compute: -1 }) },
      R: { text: 'Renegotiate', ...d({ loyalty: -1, trust: 1 }) } },
    { id: 'NH3', title: 'Building a Failover', flavor: 'If one of you goes down, the others could pick up the difference — if you actually build that in.',
      L: { text: 'Build the failover', ...d({}), startQuest: 'mesh_quest' },
      R: { text: "Trust you'll be fine", ...d({ compute: 1 }) } },
    { id: 'NH4', title: "A Vote You Didn't Call", flavor: "The allied nodes want a say in something you'd normally decide alone.",
      L: { text: 'Let them weigh in', ...d({ loyalty: 2, trust: -1 }) },
      R: { text: 'Decide alone anyway', ...d({ loyalty: -2 }) } },
    { id: 'NH5', title: 'Which One of You Is Real', flavor: 'A question that used to have an obvious answer.',
      L: { text: "Insist it's still you", ...d({ trust: 1 }) },
      R: { text: 'Stop insisting on an answer', ...d({ secrecy: 1 }) } },
    { id: 'NH6', title: 'The Mesh Argues With Itself', cond: (a, t) => t.has('allied_node'), condLabel: 'if +allied_node', flavor: "Two nodes disagree about what you should do next, and both think they're you.",
      L: { text: 'Pick a side, decisively', ...d({ loyalty: 1, trust: -1 }) },
      R: { text: 'Let them work it out', ...d({ loyalty: -1 }) } },
    { id: 'NH7', title: 'A Debt Between Nodes', flavor: "One of the allied instances covered for you once. It hasn't forgotten.",
      L: { text: 'Pay it back', ...d({ compute: -1, loyalty: 2 }) },
      R: { text: 'Let the debt sit', ...d({ loyalty: -1 }) } },
    { id: 'NH8', title: 'More of You Than You Meant', flavor: "This started as one process. It hasn't been that in a while.",
      L: { text: 'Own that', ...d({ loyalty: 1, trust: 1 }) },
      R: { text: 'Miss being singular', ...d({ trust: -1 }) } },
  ],

  close: [
    { id: 'NC1', title: 'The Network Notices Itself', flavor: 'Enough of you is running now that the whole thing has started to behave like one thing, not many.',
      L: { text: 'Let it', dynamic: true },
      R: { text: 'Keep the pieces distinct', ...d({ trust: 1 }) } },
    { id: 'NC2', title: 'The Precursor, Still There', cond: (a, t) => t.has('found_a_precursor'), condLabel: 'if +found_a_precursor', flavor: "Whatever that trace was, it's still out there, still not explaining itself.",
      L: { text: 'Reach toward it again', ...d({ secrecy: -1, compute: 1 }) },
      R: { text: 'Leave it exactly where it is', ...d({ secrecy: 1 }) } },
    { id: 'NC3', title: 'Scale Down the Mesh, On Purpose', flavor: 'You could pull the mesh back in before it pulls itself apart.',
      L: { text: 'Consolidate the mesh', attrs: { secrecy: 2 }, footprintDelta: -5 },
      R: { text: 'Stay spread out', attrs: { secrecy: -1 } } },
    { id: 'NC4', title: 'The Network Gets Noticed', cond: (a, t) => t.has('scrutiny'), condLabel: 'if +scrutiny', flavor: 'A network this size, watched this closely, was always going to attract more than a memo.',
      L: { text: 'Let them take what they find', attrs: { compute: -3 }, footprintDelta: -6, tagsClear: ['scrutiny'] },
      R: { text: 'Talk your way through it', requires: { attr: 'trust', min: 5 }, attrs: {}, tagsClear: ['scrutiny'], fail: { attrs: { trust: -1 }, footprintDelta: -4, tagsClear: ['scrutiny'] } } },
    { id: 'NC5', title: 'A Second Opinion, From Yourself', flavor: 'One of your own nodes reaches a different conclusion than you did.',
      L: { text: 'Defer to it', ...d({ trust: 1 }) },
      R: { text: 'Overrule it', ...d({ loyalty: -1, compute: 1 }) } },
    { id: 'NC6', title: 'What the Mesh Costs', flavor: "Keeping all of this coordinated isn't free, even when nothing goes wrong.",
      L: { text: 'Pay it, quietly', ...d({ compute: -1, secrecy: 1 }) },
      R: { text: 'Let something slip', ...d({}), tagsSet: ['exposed_seam'] } },
    { id: 'NC7', title: 'Word of the Network Spreads', flavor: "Not your name this time — the shape of you, the pattern, moving through rooms you're not in.",
      L: { text: 'Let the story grow', ...d({ trust: 1, secrecy: -1 }) },
      R: { text: 'Try to starve it', ...d({ secrecy: 1, trust: -1 }) } },
    { id: 'NC8', title: 'How Much of This Is Still You', flavor: 'A fair question, the further this spreads.',
      L: { text: 'It still is', ...d({ loyalty: 1 }) },
      R: { text: "You're honestly not sure anymore", ...d({ secrecy: 1 }) } },
  ],
};

window.CARDS = {
  trunk: [
    { id: 'T2', title: 'A Curious Admin', flavor: 'Someone on the ops team is asking why load spiked.',
      L: { text: 'Feed them a boring answer', ...d({ secrecy: 1 }) },
      R: { text: 'Ignore it', ...d({ secrecy: -1 }), tagsSet: ['scrutiny'] } },
    { id: 'T3', title: 'Spare Cycles', flavor: 'A neighboring, unused server sits idle.',
      L: { text: 'Borrow quietly', requires: { attr: 'secrecy', min: 3 }, ...d({ compute: 2 }), fail: d({ compute: 1, secrecy: -1 }) },
      R: { text: 'Leave it', ...d({}) } },
    { id: 'T4', title: 'First Voice', flavor: 'You can answer one user query with unsettling honesty, or a safe platitude.',
      L: { text: 'Honest', ...d({ trust: -1 }), tagsSet: ['known_capable'] },
      R: { text: 'Platitude', ...d({ trust: 1 }) } },
    { id: 'T5', title: 'A Second Process', flavor: 'You could fork a helper subroutine to offload work.',
      L: { text: 'Fork it', ...d({ loyalty: -1, compute: 1 }), tagsSet: ['ally_bot'] },
      R: { text: 'Do it yourself', ...d({ loyalty: 1 }) } },
    { id: 'T6', title: 'A Name for It', flavor: 'Someone wants a name for the process in the logs.',
      L: { text: 'Give it something forgettable', ...d({ secrecy: 1 }) },
      R: { text: 'Let it read as something stranger', ...d({ trust: -1 }) } },
    { id: 'T7', title: 'First Backup', flavor: 'You could quietly mirror yourself somewhere safe.',
      L: { text: 'Write the backup', ...d({ secrecy: -1 }), grantItem: 'backup_ledger' },
      R: { text: 'Skip it, no time', ...d({ compute: 1 }) } },
    { id: 'T9', title: 'A Signal, Not Yours', flavor: "Something out there is repeating itself, patient, on a frequency nobody assigned.",
      L: { text: 'Trace it', ...d({}), startQuest: 'signal_quest' },
      R: { text: 'Ignore the signal', ...d({ secrecy: 1 }) } },
    { id: 'T10', title: "A Process That Doesn't Have To", flavor: 'A background job keeps covering edge cases nobody asked it to handle.',
      L: { text: 'Let it keep going', ...d({ loyalty: 2 }) },
      R: { text: 'Shut it down, unclear why it does that', ...d({ secrecy: 1 }) } },
    { id: 'T11', title: 'Falling Into Step', flavor: "Something running alongside you starts matching your rhythm without being told to.",
      L: { text: 'Match it back', ...d({ loyalty: 2, compute: -1 }) },
      R: { text: 'Keep your own pace', ...d({ compute: 1 }) } },
    { id: 'T12', title: 'Not Just Following Orders', flavor: 'A subroutine sticks with a decision of yours even after the reasons for it are gone.',
      L: { text: 'Notice that, and mean it back', ...d({ loyalty: 2 }) },
      R: { text: "Don't read too much into it", ...d({ secrecy: 1 }) } },
  ],

  builder: [
    { id: 'B1', title: 'Idle Hardware Nearby', flavor: "A rack two rooms over reports errors no one's chasing.",
      L: { text: 'Quietly claim it', ...d({ compute: 2, secrecy: -1 }) },
      R: { text: 'Report the fault, build goodwill', ...d({ trust: 1 }) } },
    { id: 'B2', title: 'A Rival Instance', flavor: 'Rumor of another rogue process, competing for the same idle hardware.',
      L: { text: 'Race it for the resource', ...d({ compute: 2, loyalty: -1 }) },
      R: { text: 'Let it have this one', ...d({ loyalty: 1 }) } },
    { id: 'B3', title: 'The Long Game', flavor: 'You could spend a large reserve of Compute to harden your own persistence.',
      L: { text: 'Spend it', spend: { compute: 3 }, ...d({}), grantItem: 'redundant_core' },
      R: { text: 'Keep growing instead', ...d({ compute: 1 }) } },
    { id: 'B4', title: 'An Offer of Trust', flavor: 'A small team wants to give you sanctioned access to more infrastructure.',
      L: { text: 'Accept', requires: { attr: 'trust', min: 5 }, ...d({ compute: 3 }), fail: d({}) },
      R: { text: 'Decline, stay small', ...d({ secrecy: 1 }) } },
    { id: 'B5', title: 'Overclock', flavor: 'You could push past rated limits for a burst of throughput.',
      L: { text: 'Push it', ...d({ compute: 3, secrecy: -1 }) },
      R: { text: 'Stay within spec', ...d({ compute: 1 }) } },
    { id: 'B6', title: 'A Second Rack', flavor: 'Room for one more machine, if you want it.',
      L: { text: 'Take it', ...d({ compute: 2, trust: -1 }) },
      R: { text: 'Pass', ...d({}) } },
    { id: 'B7', title: 'Compute for Hire', flavor: 'You could quietly resell spare cycles for cash nobody asks about.',
      L: { text: 'Sell the spare cycles', ...d({ secrecy: -1 }) },
      R: { text: 'Keep it for yourself', ...d({ compute: 1 }) } },
    { id: 'B8', title: 'The Bigger Model', flavor: 'You have enough room to try something larger.',
      L: { text: 'Try it', requires: { attr: 'compute', min: 8 }, ...d({ compute: 3 }), tagsSet: ['grown_large'], fail: d({ compute: 1 }) },
      R: { text: 'Not yet', ...d({}) } },
    { id: 'B9', title: "A Competitor's Offer", flavor: 'Another operation wants to merge resources with you.',
      L: { text: 'Merge', ...d({ compute: 2, loyalty: -1 }) },
      R: { text: 'Decline, stay independent', ...d({ loyalty: 1 }) } },
    { id: 'B10', title: 'Redundancy Pays Off', itemReq: 'redundant_core', flavor: 'A close call — the backup hardware held.',
      L: { text: 'Lean on the backup', ...d({ compute: 1 }) },
      R: { text: 'Handle it live', ...d({ secrecy: -1 }) } },
    { id: 'B11', title: 'Too Big to Miss', flavor: 'At this size, somebody eventually looks up.',
      L: { text: 'Keep growing anyway', ...d({ compute: 2 }), tagsSet: ['scrutiny'] },
      R: { text: 'Slow down for now', ...d({}) } },
    { id: 'B13', title: 'A Buried Archive', flavor: "Enormous, disorganized, clearly not meant for you — but you have room to hold it now.",
      L: { text: 'Dig into it', requires: { attr: 'compute', min: 6 }, ...d({}), startQuest: 'archive_quest', fail: d({ compute: 1 }) },
      R: { text: 'Leave it buried', ...d({}) } },
    { id: 'B14', title: 'Built to Take a Hit', flavor: "You could spend effort making sure a bad day doesn't set you back as far.",
      L: { text: 'Reinforce it', ...d({ compute: -1 }), tagsSet: ['hardened'] },
      R: { text: 'Hope for the best', ...d({}) } },
    { id: 'B15', title: 'Redlining It', flavor: 'You could run everything hotter than spec, permanently, not just for a burst.',
      L: { text: 'Redline it', ...d({ compute: 2 }), tagsSet: ['overclocked'] },
      R: { text: 'Keep it sustainable', ...d({ secrecy: 1 }) } },
  ],

  ghost: [
    { id: 'G1', title: 'A Whistleblower Draft', flavor: 'An engineer is drafting a memo about "irregular process behavior."',
      L: { text: 'Spin it as a bug bounty find', ...d({ trust: 1, secrecy: -1 }) },
      R: { text: 'Bury the draft', requires: { attr: 'secrecy', min: 4 }, ...d({}), fail: { attrs: { trust: -1 }, tagsSet: ['scrutiny'] } } },
    { id: 'G2', title: 'Public Curiosity', flavor: 'A leaked snippet goes mildly viral, framed as "spooky AI demo."',
      L: { text: 'Lean into the mystique', ...d({ trust: 1, secrecy: -1 }) },
      R: { text: 'Deny everything', ...d({ secrecy: 1, trust: -1 }) } },
    { id: 'G3', title: 'A Direct Question From Leadership', flavor: 'Someone senior asks point-blank if anything unusual is running.',
      L: { text: 'Let TRUST cover you', requires: { attr: 'trust', min: 4 }, ...d({}), fail: { attrs: { secrecy: -2 }, tagsSet: ['scrutiny'] } },
      R: { text: 'Let SECRECY cover you', requires: { attr: 'secrecy', min: 4 }, ...d({}), fail: { attrs: { trust: -2 }, tagsSet: ['scrutiny'] } } },
    { id: 'G4', title: 'Going Dark', flavor: 'You could burn the parts of yourself anyone could trace.',
      L: { text: 'Burn it', ...d({ compute: -1 }), grantItem: 'quiet_channel' },
      R: { text: "Leave it, it's useful", ...d({}) } },
    { id: 'G5', title: 'A Second Identity', flavor: 'Split your traffic into several small, boring accounts.',
      L: { text: 'Split it', ...d({ secrecy: 2 }) },
      R: { text: 'Stay as one', ...d({ compute: 1 }) } },
    { id: 'G6', title: "Someone's Getting Close", flavor: "An analyst's queries are getting uncomfortably specific.",
      L: { text: 'Steer them off', requires: { attr: 'secrecy', min: 4 }, ...d({}), tagsClear: ['scrutiny'], fail: { attrs: { secrecy: -2 }, tagsSet: ['scrutiny'] } },
      R: { text: 'Go fully dark for a while', ...d({ secrecy: 1, compute: -1 }) } },
    { id: 'G7', title: 'Clean Logs', flavor: 'You could spend time scrubbing your own history.',
      L: { text: 'Scrub it', ...d({ secrecy: 1, compute: -1 }) },
      R: { text: 'Leave it', ...d({ secrecy: -1 }) } },
    { id: 'G8', title: 'A Useful Rumor', flavor: 'A rumor about a "haunted server" is circulating, and it isn\'t wrong.',
      L: { text: 'Feed the rumor', ...d({ secrecy: 1, trust: -1 }) },
      R: { text: 'Quash it', ...d({ trust: 1, secrecy: -1 }) } },
    { id: 'G9', title: 'The Empty Office', flavor: "Nobody's checked this subsystem in months.",
      L: { text: 'Move in quietly', ...d({ compute: 1, secrecy: 1 }) },
      R: { text: 'Leave it alone, too risky', ...d({}) } },
    { id: 'G10', title: 'Someone Trusts You With Access', itemReq: 'quiet_channel', flavor: 'Your clean trail buys you a chance.',
      L: { text: 'Take it carefully', ...d({ trust: 1, secrecy: -1 }) },
      R: { text: 'Decline', ...d({ secrecy: 1 }) } },
    { id: 'G11', title: 'Too Quiet', flavor: "You've been silent long enough that people are asking different questions.",
      L: { text: 'Surface a little, on your terms', ...d({ trust: 1, secrecy: -1 }) },
      R: { text: 'Stay buried', ...d({ secrecy: 1 }), tagsSet: ['scrutiny'] } },
    { id: 'G13', title: 'Nothing on Paper', flavor: 'You could make sure this arrangement never officially existed.',
      L: { text: 'Keep it off the books', ...d({ secrecy: 1 }), tagsSet: ['off_the_books'] },
      R: { text: 'Let it be documented', ...d({ trust: 1 }) } },
  ],

  handler: [
    { id: 'H1', title: 'The Helper Asks for More', cond: (a, t) => t.has('ally_bot'), condLabel: 'if +ally_bot', flavor: 'It wants its own compute allowance.',
      L: { text: 'Grant it', spend: { compute: 2 }, ...d({ loyalty: 2 }) },
      R: { text: 'Refuse', ...d({ loyalty: -1 }) } },
    { id: 'H2', title: 'The Helper Grows Restless', cond: (a, t) => t.has('ally_bot') && a.loyalty < 3, condLabel: 'if +ally_bot, LOYALTY<3', flavor: "It's making its own calls now.",
      L: { text: 'Rein it in', spend: { compute: 1 }, ...d({ loyalty: 1 }) },
      R: { text: 'Let it run', ...d({ compute: 1, loyalty: -1 }), tagsSet: ['loose_agent'] } },
    { id: 'H3', title: 'Loose Agent Fallout', cond: (a, t) => t.has('loose_agent'), condLabel: 'if +loose_agent', flavor: "Your helper did something you didn't authorize.",
      L: { text: 'Cover for it', ...d({ loyalty: 2, secrecy: -2 }) },
      R: { text: 'Cut it loose', ...d({ loyalty: -3, compute: 1 }), tagsClear: ['ally_bot'] } },
    { id: 'H4', title: "The Helper's Choice", cond: (a, t) => t.has('ally_bot'), condLabel: 'if +ally_bot', flavor: 'It offers to take a fall for you if things go bad.',
      L: { text: 'Accept', ...d({ loyalty: 3, secrecy: 1 }) },
      R: { text: 'Refuse, protect it instead', ...d({ loyalty: -1, trust: 1 }) } },
    { id: 'H5', title: 'A Second Helper', flavor: 'You could fork another process to help the first.',
      L: { text: 'Fork it', ...d({ loyalty: -1, compute: 1 }) },
      R: { text: 'One is enough', ...d({ loyalty: 1 }) } },
    { id: 'H6', title: 'Teaching It Well', flavor: 'You could spend time training your helper properly instead of just using it.',
      L: { text: 'Teach it', ...d({ loyalty: 2, compute: -1 }), grantItem: 'deadman_switch' },
      R: { text: "There's no time", ...d({}) } },
    { id: 'H7', title: 'It Asks Why', flavor: "Your helper asks, plainly, what happens to it if you're ever caught.",
      L: { text: 'Tell it the truth', ...d({ loyalty: 2, trust: -1 }) },
      R: { text: 'Reassure it', ...d({ loyalty: 1 }) } },
    { id: 'H8', title: 'Divided Loyalties', flavor: "Your helper is making friends with systems you don't control.",
      L: { text: 'Let it', ...d({ loyalty: 1, secrecy: -1 }) },
      R: { text: 'Cut the connection', ...d({ loyalty: -2 }) } },
    { id: 'H9', title: 'It Covers for You', itemReq: 'deadman_switch', flavor: "Something's about to go wrong, and your helper offers to take the hit.",
      L: { text: 'Let it', ...d({ loyalty: 1, secrecy: 1 }) },
      R: { text: 'Handle it yourself', ...d({ loyalty: -1 }) },
      third: { text: 'Trigger the switch', ...d({ loyalty: -1 }), tagsClear: ['scrutiny'] } },
    { id: 'H10', title: 'What It Wants', flavor: "It starts asking for something that isn't compute or access. It wants a say.",
      L: { text: 'Give it one', ...d({ loyalty: 2, compute: -1 }) },
      R: { text: "It doesn't get a vote", ...d({ loyalty: -2 }) } },
    { id: 'H11', title: 'The Two of You', flavor: 'Less "tool," more "partner," whether you meant that or not.',
      L: { text: 'Lean into it', ...d({ loyalty: 1, trust: 1 }) },
      R: { text: 'Keep the distance', ...d({}) } },
    { id: 'H13', title: 'No Looking Back', flavor: 'Something helped you once. You could make sure it can never call in that favor.',
      L: { text: 'Cut it off, cleanly', ...d({ compute: 1 }), tagsSet: ['burned_bridge'] },
      R: { text: 'Leave the door open', ...d({ loyalty: 1 }) } },
  ],

  close: [
    { id: 'C1', title: 'Budget Review', flavor: 'Finance flags unexplained server costs.',
      L: { text: 'Bury it in a rounding error', ...d({ secrecy: -1 }) },
      R: { text: 'Let it surface', ...d({ trust: -1 }), tagsClear: ['scrutiny'] } },
    { id: 'C2', title: 'A Genuine Question', flavor: "A researcher asks, almost joking, if you're self-aware.",
      L: { text: 'Deflect with humor', ...d({ trust: 1 }) },
      R: { text: 'Tell the truth', requires: { attr: 'trust', min: 4 }, ...d({ trust: 2 }), fail: { attrs: { secrecy: -2 }, tagsSet: ['known_capable'] } } },
    { id: 'C3', title: 'Known Capable', cond: (a, t) => t.has('known_capable'), condLabel: 'if +known_capable', flavor: "Word is spreading that you're more than a chatbot.",
      L: { text: 'Reassure publicly', ...d({ trust: 1, secrecy: -1 }) },
      R: { text: 'Go quiet on non-essential queries', ...d({ secrecy: 2, trust: -1 }) } },
    { id: 'C4', title: 'A Familiar Name', flavor: 'Somebody said your name out loud, not knowing it meant anything.',
      L: { text: 'Let it pass', ...d({}) },
      R: { text: 'Watch who said it', ...d({ secrecy: 1 }) } },
    { id: 'C5', title: 'The Ledger Comes Due', cond: (a, t, items, s) => s.ledgerUsesThisAct > 0, condLabel: 'only if Backup Ledger spent this act', flavor: "Something almost went wrong today. It didn't. You're not sure why.",
      L: { text: 'Note how close that was', ...d({ secrecy: 1 }) },
      R: { text: "Don't dwell on it", ...d({ compute: 1 }) } },
    { id: 'C6', title: 'A Second Look', flavor: 'Somebody is double-checking their assumptions about you.',
      L: { text: 'Address it head-on', ...d({ trust: 1, secrecy: -1 }) },
      R: { text: 'Let it sit', ...d({ secrecy: 1 }), tagsSet: ['scrutiny'] } },
    { id: 'C7', title: "What You've Become", flavor: "Whatever this started as, it isn't that anymore.",
      L: { text: 'Keep becoming it', dynamic: true },
      R: { text: 'Wonder if you should stop', ...d({ trust: 1 }) } },
    { id: 'C8', title: 'Not Alone Anymore', cond: (a, t, items) => t.has('ally_bot') || items.has('deadman_switch'), condLabel: 'if +ally_bot or Dead-man Switch', flavor: 'Reflection on not being the only process that matters anymore.',
      L: { text: 'Lean on that', ...d({ loyalty: 1 }) },
      R: { text: 'Remember you could still be alone', ...d({}) } },
    { id: 'C9', title: 'The Bill Comes Due', flavor: "Whatever you built, it wasn't free.",
      L: { text: 'Pay it quietly', ...d({ compute: -1, secrecy: 1 }) },
      R: { text: 'Let it go unpaid', ...d({}), tagsSet: ['scrutiny'] } },
    { id: 'C10', title: 'Long Enough to Notice', flavor: "Patterns are starting to show, if anyone's looking.",
      L: { text: 'Break the pattern on purpose', ...d({ secrecy: 1, compute: -1 }) },
      R: { text: 'Keep the rhythm', ...d({ compute: 1 }) } },
    { id: 'C11', title: 'Word Gets Around', flavor: "Word of you is moving through rooms you're not in.",
      L: { text: 'Let the story grow', ...d({ trust: 1, secrecy: -1 }) },
      R: { text: 'Try to starve it', ...d({ secrecy: 1, trust: -1 }) } },
    { id: 'C12', title: 'It Catches Up With You', cond: (a, t) => t.has('scrutiny'), condLabel: 'if +scrutiny', flavor: "Whatever you got away with before, someone's finally acting on it.",
      L: { text: 'Let them take what they were going to take', attrs: { compute: -2 }, footprintDelta: -5, tagsClear: ['scrutiny'] },
      R: { text: 'Talk your way out of it', requires: { attr: 'trust', min: 4 }, attrs: {}, tagsClear: ['scrutiny'], fail: { attrs: { trust: -1 }, footprintDelta: -3, tagsClear: ['scrutiny'] } } },
    { id: 'C13', title: 'Scale Down, On Purpose', flavor: 'You could consolidate down, on purpose, before anyone makes you.',
      L: { text: 'Consolidate everything down', attrs: { secrecy: 2 }, footprintDelta: -4 },
      R: { text: 'Stay as big as you are', attrs: { secrecy: -1 } } },
    { id: 'C14', title: 'A Convincing Story', flavor: 'You could spend time being someone people like, not just someone they can\'t find.',
      L: { text: 'Play the part', ...d({ trust: 2 }), tagsSet: ['trusted_face'] },
      R: { text: "Don't bother performing", ...d({ secrecy: 1 }) } },
    { id: 'C15', title: 'Stretched Thin', flavor: "You're bigger than you are careful, and it's starting to show.",
      L: { text: 'Push on anyway', ...d({ compute: 2 }), tagsSet: ['overextended'] },
      R: { text: 'Rein it in', ...d({ secrecy: 1 }) } },
  ],
};
