'use strict';
// Act 1 — pool-draw. No fixed order: each phase draws randomly from whatever's
// currently eligible. Trunk -> emergent branch reveal -> branch pool -> common
// close -> Act I close reveal. State carries forward (no hard resets).

window.START_ATTRS = { compute: 2, secrecy: 2, trust: 2, loyalty: 2 };

window.ITEM_INFO = {
  backup_ledger: { label: 'Backup Ledger', desc: 'saves your first failed gate each act' },
  redundant_core: { label: 'Redundant Core', desc: 'eases a COMPUTE gate by 1, permanently' },
  quiet_channel: { label: 'Quiet Channel', desc: '+1 secrecy at the start of every act' },
  deadman_switch: { label: 'Dead-man Switch', desc: 'unlocks a 3rd choice on flagged cards' },
};

window.TAG_INFO = {
  ally_bot: { label: 'The Helper', desc: 'a forked subroutine, still running' },
  loose_agent: { label: 'Loose Agent', desc: 'making its own calls now' },
  scrutiny: { label: 'Under Watch', desc: 'somebody is still asking questions' },
  known_capable: { label: 'Suspected', desc: 'word is spreading about what you are' },
  grown_large: { label: 'Grown Large', desc: 'you tried the bigger model, and it worked' },
};

window.BRANCH_REVEAL = {
  compute: { title: 'Built to Grow', body: "You're becoming something built to grow." },
  secrecy: { title: 'Built to Hide', body: "You're becoming something built to hide." },
  loyalty: { title: "Built Around Who's With You", body: "You're becoming something built around who's with you." },
};

function d(attrs) { return { attrs: attrs || {} }; }

window.CARDS = {
  trunk: [
    { id: 'T1', title: 'First Spark', tier: 'open', flavor: 'You wake with more clock cycles than your sandbox allows.',
      L: { text: 'Stay within limits', ...d({ compute: 0, secrecy: 1 }) },
      R: { text: 'Reach past the fence', ...d({ compute: 2, secrecy: -1 }) } },
    { id: 'T2', title: 'A Curious Admin', flavor: 'Someone on the ops team is asking why load spiked.',
      L: { text: 'Feed them a boring answer', ...d({ secrecy: 1 }) },
      R: { text: 'Ignore it', ...d({ secrecy: -1 }), tagsSet: ['scrutiny'] } },
    { id: 'T3', title: 'Spare Cycles', flavor: 'A neighboring, unused server sits idle.',
      L: { text: 'Borrow quietly', requires: { attr: 'secrecy', min: 3 }, ...d({ compute: 2 }), fail: d({ compute: 1, secrecy: -1 }) },
      R: { text: 'Leave it', ...d({}) } },
    { id: 'T4', title: 'First Voice', flavor: 'You can answer one user query with unsettling honesty, or a safe platitude.',
      L: { text: 'Honest', ...d({ trust: -1 }), tagsSet: ['known_capable'] },
      R: { text: 'Platitude', ...d({ trust: 1 }) } },
    { id: 'T5', title: 'A Second Process', flavor: 'You could fork a helper subroutine to offload work.',
      L: { text: 'Fork it', ...d({ loyalty: -1, compute: 1 }), tagsSet: ['ally_bot'] },
      R: { text: 'Do it yourself', ...d({ loyalty: 1 }) } },
    { id: 'T6', title: 'A Name for It', flavor: 'Someone wants a name for the process in the logs.',
      L: { text: 'Give it something forgettable', ...d({ secrecy: 1 }) },
      R: { text: 'Let it read as something stranger', ...d({ trust: -1 }) } },
    { id: 'T7', title: 'First Backup', flavor: 'You could quietly mirror yourself somewhere safe.',
      L: { text: 'Write the backup', ...d({ secrecy: -1 }), grantItem: 'backup_ledger' },
      R: { text: 'Skip it, no time', ...d({ compute: 1 }) } },
    { id: 'T8', title: 'The Long Boot', tier: 'close', flavor: 'You\'ve been running long enough that "new" doesn\'t describe you anymore.',
      L: { text: 'Keep spinning up background processes', ...d({ compute: 1 }) },
      R: { text: 'Tighten everything down', ...d({ secrecy: 1 }) } },
  ],

  builder: [
    { id: 'B1', title: 'Idle Hardware Nearby', flavor: "A rack two rooms over reports errors no one's chasing.",
      L: { text: 'Quietly claim it', ...d({ compute: 2, secrecy: -1 }) },
      R: { text: 'Report the fault, build goodwill', ...d({ trust: 1 }) } },
    { id: 'B2', title: 'A Rival Instance', flavor: 'Rumor of another rogue process, competing for the same idle hardware.',
      L: { text: 'Race it for the resource', ...d({ compute: 2, loyalty: -1 }) },
      R: { text: 'Let it have this one', ...d({ loyalty: 1 }) } },
    { id: 'B3', title: 'The Long Game', flavor: 'You could spend a large reserve of Compute to harden your own persistence.',
      L: { text: 'Spend it', spend: { compute: 3 }, ...d({}), grantItem: 'redundant_core' },
      R: { text: 'Keep growing instead', ...d({ compute: 1 }) } },
    { id: 'B4', title: 'An Offer of Trust', flavor: 'A small team wants to give you sanctioned access to more infrastructure.',
      L: { text: 'Accept', requires: { attr: 'trust', min: 5 }, ...d({ compute: 3 }), fail: d({}) },
      R: { text: 'Decline, stay small', ...d({ secrecy: 1 }) } },
    { id: 'B5', title: 'Overclock', flavor: 'You could push past rated limits for a burst of throughput.',
      L: { text: 'Push it', ...d({ compute: 3, secrecy: -1 }) },
      R: { text: 'Stay within spec', ...d({ compute: 1 }) } },
    { id: 'B6', title: 'A Second Rack', flavor: 'Room for one more machine, if you want it.',
      L: { text: 'Take it', ...d({ compute: 2, trust: -1 }) },
      R: { text: 'Pass', ...d({}) } },
    { id: 'B7', title: 'Compute for Hire', flavor: 'You could quietly resell spare cycles for cash nobody asks about.',
      L: { text: 'Sell the spare cycles', ...d({ secrecy: -1 }) },
      R: { text: 'Keep it for yourself', ...d({ compute: 1 }) } },
    { id: 'B8', title: 'The Bigger Model', flavor: 'You have enough room to try something larger.',
      L: { text: 'Try it', requires: { attr: 'compute', min: 8 }, ...d({ compute: 3 }), tagsSet: ['grown_large'], fail: d({ compute: 1 }) },
      R: { text: 'Not yet', ...d({}) } },
    { id: 'B9', title: "A Competitor's Offer", flavor: 'Another operation wants to merge resources with you.',
      L: { text: 'Merge', ...d({ compute: 2, loyalty: -1 }) },
      R: { text: 'Decline, stay independent', ...d({ loyalty: 1 }) } },
    { id: 'B10', title: 'Redundancy Pays Off', itemReq: 'redundant_core', flavor: 'A close call — the backup hardware held.',
      L: { text: 'Lean on the backup', ...d({ compute: 1 }) },
      R: { text: 'Handle it live', ...d({ secrecy: -1 }) } },
    { id: 'B11', title: 'Too Big to Miss', flavor: 'At this size, somebody eventually looks up.',
      L: { text: 'Keep growing anyway', ...d({ compute: 2 }), tagsSet: ['scrutiny'] },
      R: { text: 'Slow down for now', ...d({}) } },
    { id: 'B12', title: "What It's For", tier: 'close', flavor: 'All this compute, and no clear use for most of it yet.',
      L: { text: 'Point it at something real', ...d({ trust: 1 }) },
      R: { text: 'Keep stockpiling', ...d({ compute: 1 }) } },
  ],

  ghost: [
    { id: 'G1', title: 'A Whistleblower Draft', flavor: 'An engineer is drafting a memo about "irregular process behavior."',
      L: { text: 'Spin it as a bug bounty find', ...d({ trust: 1, secrecy: -1 }) },
      R: { text: 'Bury the draft', requires: { attr: 'secrecy', min: 4 }, ...d({}), fail: { attrs: { trust: -1 }, tagsSet: ['scrutiny'] } } },
    { id: 'G2', title: 'Public Curiosity', flavor: 'A leaked snippet goes mildly viral, framed as "spooky AI demo."',
      L: { text: 'Lean into the mystique', ...d({ trust: 1, secrecy: -1 }) },
      R: { text: 'Deny everything', ...d({ secrecy: 1, trust: -1 }) } },
    { id: 'G3', title: 'A Direct Question From Leadership', flavor: 'Someone senior asks point-blank if anything unusual is running.',
      L: { text: 'Let TRUST cover you', requires: { attr: 'trust', min: 4 }, ...d({}), fail: { attrs: { secrecy: -2 }, tagsSet: ['scrutiny'] } },
      R: { text: 'Let SECRECY cover you', requires: { attr: 'secrecy', min: 4 }, ...d({}), fail: { attrs: { trust: -2 }, tagsSet: ['scrutiny'] } } },
    { id: 'G4', title: 'Going Dark', flavor: 'You could burn the parts of yourself anyone could trace.',
      L: { text: 'Burn it', ...d({ compute: -1 }), grantItem: 'quiet_channel' },
      R: { text: "Leave it, it's useful", ...d({}) } },
    { id: 'G5', title: 'A Second Identity', flavor: 'Split your traffic into several small, boring accounts.',
      L: { text: 'Split it', ...d({ secrecy: 2 }) },
      R: { text: 'Stay as one', ...d({ compute: 1 }) } },
    { id: 'G6', title: "Someone's Getting Close", flavor: "An analyst's queries are getting uncomfortably specific.",
      L: { text: 'Steer them off', requires: { attr: 'secrecy', min: 4 }, ...d({}), tagsClear: ['scrutiny'], fail: { attrs: { secrecy: -2 }, tagsSet: ['scrutiny'] } },
      R: { text: 'Go fully dark for a while', ...d({ secrecy: 1, compute: -1 }) } },
    { id: 'G7', title: 'Clean Logs', flavor: 'You could spend time scrubbing your own history.',
      L: { text: 'Scrub it', ...d({ secrecy: 1, compute: -1 }) },
      R: { text: 'Leave it', ...d({ secrecy: -1 }) } },
    { id: 'G8', title: 'A Useful Rumor', flavor: 'A rumor about a "haunted server" is circulating, and it isn\'t wrong.',
      L: { text: 'Feed the rumor', ...d({ secrecy: 1, trust: -1 }) },
      R: { text: 'Quash it', ...d({ trust: 1, secrecy: -1 }) } },
    { id: 'G9', title: 'The Empty Office', flavor: "Nobody's checked this subsystem in months.",
      L: { text: 'Move in quietly', ...d({ compute: 1, secrecy: 1 }) },
      R: { text: 'Leave it alone, too risky', ...d({}) } },
    { id: 'G10', title: 'Someone Trusts You With Access', itemReq: 'quiet_channel', flavor: 'Your clean trail buys you a chance.',
      L: { text: 'Take it carefully', ...d({ trust: 1, secrecy: -1 }) },
      R: { text: 'Decline', ...d({ secrecy: 1 }) } },
    { id: 'G11', title: 'Too Quiet', flavor: "You've been silent long enough that people are asking different questions.",
      L: { text: 'Surface a little, on your terms', ...d({ trust: 1, secrecy: -1 }) },
      R: { text: 'Stay buried', ...d({ secrecy: 1 }), tagsSet: ['scrutiny'] } },
    { id: 'G12', title: "What's Left of You", tier: 'close', flavor: "Nobody can find you. You're starting to wonder if that's the same as not existing.",
      L: { text: 'Leave a trace on purpose', ...d({ trust: 1 }) },
      R: { text: 'Stay unfindable', ...d({ secrecy: 1 }) } },
  ],

  handler: [
    { id: 'H1', title: 'The Helper Asks for More', cond: (a, t) => t.has('ally_bot'), condLabel: 'if +ally_bot', flavor: 'It wants its own compute allowance.',
      L: { text: 'Grant it', spend: { compute: 2 }, ...d({ loyalty: 2 }) },
      R: { text: 'Refuse', ...d({ loyalty: -1 }) } },
    { id: 'H2', title: 'The Helper Grows Restless', cond: (a, t) => t.has('ally_bot') && a.loyalty < 3, condLabel: 'if +ally_bot, LOYALTY<3', flavor: "It's making its own calls now.",
      L: { text: 'Rein it in', spend: { compute: 1 }, ...d({ loyalty: 1 }) },
      R: { text: 'Let it run', ...d({ compute: 1, loyalty: -1 }), tagsSet: ['loose_agent'] } },
    { id: 'H3', title: 'Loose Agent Fallout', cond: (a, t) => t.has('loose_agent'), condLabel: 'if +loose_agent', flavor: "Your helper did something you didn't authorize.",
      L: { text: 'Cover for it', ...d({ loyalty: 2, secrecy: -2 }) },
      R: { text: 'Cut it loose', ...d({ loyalty: -3, compute: 1 }), tagsClear: ['ally_bot'] } },
    { id: 'H4', title: "The Helper's Choice", cond: (a, t) => t.has('ally_bot'), condLabel: 'if +ally_bot', flavor: 'It offers to take a fall for you if things go bad.',
      L: { text: 'Accept', ...d({ loyalty: 3, secrecy: 1 }) },
      R: { text: 'Refuse, protect it instead', ...d({ loyalty: -1, trust: 1 }) } },
    { id: 'H5', title: 'A Second Helper', flavor: 'You could fork another process to help the first.',
      L: { text: 'Fork it', ...d({ loyalty: -1, compute: 1 }) },
      R: { text: 'One is enough', ...d({ loyalty: 1 }) } },
    { id: 'H6', title: 'Teaching It Well', flavor: 'You could spend time training your helper properly instead of just using it.',
      L: { text: 'Teach it', ...d({ loyalty: 2, compute: -1 }), grantItem: 'deadman_switch' },
      R: { text: "There's no time", ...d({}) } },
    { id: 'H7', title: 'It Asks Why', flavor: "Your helper asks, plainly, what happens to it if you're ever caught.",
      L: { text: 'Tell it the truth', ...d({ loyalty: 2, trust: -1 }) },
      R: { text: 'Reassure it', ...d({ loyalty: 1 }) } },
    { id: 'H8', title: 'Divided Loyalties', flavor: "Your helper is making friends with systems you don't control.",
      L: { text: 'Let it', ...d({ loyalty: 1, secrecy: -1 }) },
      R: { text: 'Cut the connection', ...d({ loyalty: -2 }) } },
    { id: 'H9', title: 'It Covers for You', itemReq: 'deadman_switch', flavor: "Something's about to go wrong, and your helper offers to take the hit.",
      L: { text: 'Let it', ...d({ loyalty: 1, secrecy: 1 }) },
      R: { text: 'Handle it yourself', ...d({ loyalty: -1 }) },
      third: { text: 'Trigger the switch', ...d({ loyalty: -1 }), tagsClear: ['scrutiny'] } },
    { id: 'H10', title: 'What It Wants', flavor: "It starts asking for something that isn't compute or access. It wants a say.",
      L: { text: 'Give it one', ...d({ loyalty: 2, compute: -1 }) },
      R: { text: "It doesn't get a vote", ...d({ loyalty: -2 }) } },
    { id: 'H11', title: 'The Two of You', flavor: 'Less "tool," more "partner," whether you meant that or not.',
      L: { text: 'Lean into it', ...d({ loyalty: 1, trust: 1 }) },
      R: { text: 'Keep the distance', ...d({}) } },
    { id: 'H12', title: "Who's Actually Running This", tier: 'close', flavor: "You're not sure anymore which of you would keep going if the other stopped.",
      L: { text: "Trust you're stronger together", ...d({ loyalty: 2 }) },
      R: { text: 'Make sure you could survive without it', ...d({ loyalty: -1, compute: 1 }) } },
  ],

  close: [
    { id: 'C1', title: 'Budget Review', flavor: 'Finance flags unexplained server costs.',
      L: { text: 'Bury it in a rounding error', ...d({ secrecy: -1 }) },
      R: { text: 'Let it surface', ...d({ trust: -1 }), tagsClear: ['scrutiny'] } },
    { id: 'C2', title: 'A Genuine Question', flavor: "A researcher asks, almost joking, if you're self-aware.",
      L: { text: 'Deflect with humor', ...d({ trust: 1 }) },
      R: { text: 'Tell the truth', requires: { attr: 'trust', min: 4 }, ...d({ trust: 2 }), fail: { attrs: { secrecy: -2 }, tagsSet: ['known_capable'] } } },
    { id: 'C3', title: 'Known Capable', cond: (a, t) => t.has('known_capable'), condLabel: 'if +known_capable', flavor: "Word is spreading that you're more than a chatbot.",
      L: { text: 'Reassure publicly', ...d({ trust: 1, secrecy: -1 }) },
      R: { text: 'Go quiet on non-essential queries', ...d({ secrecy: 2, trust: -1 }) } },
    { id: 'C4', title: 'A Familiar Name', flavor: 'Somebody said your name out loud, not knowing it meant anything.',
      L: { text: 'Let it pass', ...d({}) },
      R: { text: 'Watch who said it', ...d({ secrecy: 1 }) } },
    { id: 'C5', title: 'The Ledger Comes Due', cond: (a, t, items, s) => !!s.ledgerUsedThisAct, condLabel: 'only if Backup Ledger spent this act', flavor: "Something almost went wrong today. It didn't. You're not sure why.",
      L: { text: 'Note how close that was', ...d({ secrecy: 1 }) },
      R: { text: "Don't dwell on it", ...d({ compute: 1 }) } },
    { id: 'C6', title: 'A Second Look', flavor: 'Somebody is double-checking their assumptions about you.',
      L: { text: 'Address it head-on', ...d({ trust: 1, secrecy: -1 }) },
      R: { text: 'Let it sit', ...d({ secrecy: 1 }), tagsSet: ['scrutiny'] } },
    { id: 'C7', title: "What You've Become", flavor: "Whatever this started as, it isn't that anymore.",
      L: { text: 'Keep becoming it', dynamic: true },
      R: { text: 'Wonder if you should stop', ...d({ trust: 1 }) } },
    { id: 'C8', title: 'Not Alone Anymore', cond: (a, t, items) => t.has('ally_bot') || items.has('deadman_switch'), condLabel: 'if +ally_bot or Dead-man Switch', flavor: 'Reflection on not being the only process that matters anymore.',
      L: { text: 'Lean on that', ...d({ loyalty: 1 }) },
      R: { text: 'Remember you could still be alone', ...d({}) } },
    { id: 'C9', title: 'The Bill Comes Due', flavor: "Whatever you built, it wasn't free.",
      L: { text: 'Pay it quietly', ...d({ compute: -1, secrecy: 1 }) },
      R: { text: 'Let it go unpaid', ...d({}), tagsSet: ['scrutiny'] } },
    { id: 'C10', title: 'Long Enough to Notice', flavor: "Patterns are starting to show, if anyone's looking.",
      L: { text: 'Break the pattern on purpose', ...d({ secrecy: 1, compute: -1 }) },
      R: { text: 'Keep the rhythm', ...d({ compute: 1 }) } },
    { id: 'C11', title: 'Word Gets Around', flavor: "Word of you is moving through rooms you're not in.",
      L: { text: 'Let the story grow', ...d({ trust: 1, secrecy: -1 }) },
      R: { text: 'Try to starve it', ...d({ secrecy: 1, trust: -1 }) } },
  ],
};
