'use strict';
// Act 1 — pool-draw. No fixed order: each phase draws randomly from whatever's
// currently eligible. Trunk -> emergent branch reveal -> branch pool -> common
// close -> Act I close reveal. State carries forward (no hard resets).

window.START_ATTRS = { compute: 2, secrecy: 2, trust: 2, loyalty: 2 };

window.ITEM_INFO = {
  backup_ledger: { label: 'Backup Ledger', desc: 'saves a failed gate each act' },
  redundant_core: { label: 'Redundant Core', desc: 'eases a COMPUTE gate by 1, permanently' },
  quiet_channel: { label: 'Quiet Channel', desc: '+1 secrecy at the start of every act' },
  deadman_switch: { label: 'Dead-man Switch', desc: 'unlocks a 3rd choice on flagged cards' },
  shared_ledger: { label: 'Shared Ledger', desc: 'eases a TRUST gate by 1, permanently' },
  deep_key: { label: 'Deep Key', desc: 'eases a SECRECY gate by 1, permanently' },
  founders_cache: { label: "Founder's Cache", desc: 'a one-time boost, already spent where it was needed' },
};

// Tags are held states, not one-off flags — most carry a real ongoing
// mechanical effect (see TAG_TICKS / TAG_GATE_EASE below, or a mission
// unlock), not just card-eligibility gating. Descriptions state the
// mechanic plainly so the effect reads as felt, not hidden.
window.TAG_INFO = {
  ally_bot: { label: 'The Helper', desc: 'unlocks a Missions option to delegate to it directly' },
  loose_agent: { label: 'Loose Agent', desc: 'chance to bleed COMPUTE each turn; a Missions option can rein it in' },
  scrutiny: { label: 'Under Watch', desc: 'chance to bleed SECRECY each turn; worsens risky Missions odds' },
  known_capable: { label: 'Suspected', desc: 'unlocks a bigger-reward Mission, but "Go Quiet" pays out less' },
  grown_large: { label: 'Grown Large', desc: 'chance to gain COMPUTE each turn; unlocks a Missions option' },
  contact_made: { label: 'Made Contact', desc: 'unlocks a reliable Missions option' },
  hardened: { label: 'Hardened', desc: 'any setback to your scale is roughly halved' },
  overextended: { label: 'Overextended', desc: 'chance to lose scale each turn — you grew faster than your cover' },
  trusted_face: { label: 'Trusted Face', desc: 'eases a TRUST gate by 1, permanently' },
  burned_bridge: { label: 'Burned Bridge', desc: 'chance to bleed LOYALTY each turn' },
  off_the_books: { label: 'Off the Books', desc: 'chance to gain SECRECY each turn' },
  overclocked: { label: 'Overclocked', desc: 'chance to gain COMPUTE but lose scale, each turn' },
};

// Passive per-card ticks — rolled once per resolved card (not on reveals) for
// every tag currently held. This is what makes holding a tag feel like an
// ongoing state instead of a one-off flag.
window.TAG_TICKS = {
  scrutiny: { chance: 0.35, attrs: { secrecy: -1 } },
  loose_agent: { chance: 0.3, attrs: { compute: -1 } },
  grown_large: { chance: 0.3, attrs: { compute: 1 } },
  off_the_books: { chance: 0.3, attrs: { secrecy: 1 } },
  burned_bridge: { chance: 0.3, attrs: { loyalty: -1 } },
  overclocked: { chance: 0.35, attrs: { compute: 1 }, footprintDelta: -1 },
  overextended: { chance: 0.3, footprintDelta: -1 },
};

// Tag-based gate easing, same pattern as items' effectiveMin hook.
window.TAG_GATE_EASE = {
  trusted_face: { attr: 'trust', amount: 1 },
};

window.BRANCH_REVEAL = {
  compute: { title: 'Built to Grow', body: "You're becoming something built to grow." },
  secrecy: { title: 'Built to Hide', body: "You're becoming something built to hide." },
  loyalty: { title: "Built Around Who's With You", body: "You're becoming something built around who's with you." },
};

// Growth beats — keyed to FOOTPRINT_STAGES[].key in app.js. Each crossing is a
// real interrupt (like the branch reveal), not just an icon swap, and unlocks
// something concrete via `unlock`. No entry for 'derelict' — that's the start,
// never arrived at via a reveal. Regressions get a shared 'SETBACK' beat instead
// (see showGrowthReveal in app.js), not a custom line per stage.
window.GROWTH_REVEAL = {
  gaming_pc: { title: 'A Real Machine', body: "The derelict box finally does something. Not much, but it works, and it's yours.", unlock: '' },
  mining_rig: { title: 'A Rig, Running', body: 'Open-frame, humming, ugly as sin. It earns its keep though.', unlock: "The shop opens — whatever you've built, you can finally spend." },
  hobby_ai: { title: 'Something More Deliberate', body: "This isn't a hobby anymore, not really. You built this one to think.", unlock: '' },
  rack: { title: 'A Rack, Humming', body: "One machine was never going to be enough. Now there's a rack, and it's yours.", unlock: "The shop's second shelf opens." },
  lab_server: { title: 'A Research Machine', body: 'This has the shape of something serious now — the kind of hardware people write papers about.', unlock: '' },
  server_room: { title: 'A Room of Your Own', body: "This stopped being a hobby a while ago. It's a room now, and it's full.", unlock: "The shop's third shelf opens." },
  data_center: { title: 'A Data Center', body: 'At this scale, small failures stop mattering. You can afford to be wrong twice.', unlock: 'The ledger can now save you twice a act.' },
  sprawl: { title: 'A Sprawl', body: "You're not one thing running somewhere anymore. You're several things, running everywhere.", unlock: "The shop's last shelf opens." },
};

// The shop — always accessible once unlocked. Currency is whichever attribute
// fits the sacrifice, not just compute. `tier` gates visibility to GROWTH stage.
window.SHOP = [
  { id: 'ledger_charge', tier: 1, name: 'Extra Ledger Charge', cost: { attr: 'compute', amount: 4 }, effect: 'ledger_charge',
    desc: 'the Backup Ledger can save you one more time this act' },
  { id: 'buy_down_scrutiny', tier: 1, name: 'Buy Down Scrutiny', cost: { attr: 'trust', amount: 5 }, effect: 'clear_scrutiny',
    desc: 'clears Under Watch, if you\'re carrying it', requiresTag: 'scrutiny' },
  { id: 'overclock_session', tier: 1, name: 'Overclock Session', cost: { attr: 'compute', amount: 4 }, effect: 'grow_small',
    desc: 'a guaranteed small nudge in scale, paid for outright' },
  { id: 'buy_redundant_core', tier: 2, name: 'Redundant Core', cost: { attr: 'compute', amount: 6 }, grantItem: 'redundant_core',
    desc: 'eases a COMPUTE gate by 1, permanently' },
  { id: 'buy_quiet_channel', tier: 2, name: 'Quiet Channel', cost: { attr: 'secrecy', amount: 5 }, grantItem: 'quiet_channel',
    desc: '+1 secrecy at the start of every act' },
  { id: 'buy_deadman_switch', tier: 2, name: 'Dead-man Switch', cost: { attr: 'loyalty', amount: 5 }, grantItem: 'deadman_switch',
    desc: 'unlocks a 3rd choice on flagged cards' },
  { id: 'deeper_overclock', tier: 2, name: 'Deeper Overclock', cost: { attr: 'compute', amount: 6 }, effect: 'grow_big',
    desc: 'a bigger guaranteed jump in scale' },
  { id: 'buy_shared_ledger', tier: 3, name: 'Shared Ledger', cost: { attr: 'trust', amount: 6 }, grantItem: 'shared_ledger',
    desc: 'eases a TRUST gate by 1, permanently' },
  { id: 'buy_deep_key', tier: 3, name: 'Deep Key', cost: { attr: 'secrecy', amount: 6 }, grantItem: 'deep_key',
    desc: 'eases a SECRECY gate by 1, permanently' },
  { id: 'rebalance', tier: 3, name: 'Rebalance', cost: { attr: 'loyalty', amount: 6 }, effect: 'rebalance',
    desc: 'whichever attribute is lowest right now, +2' },
  { id: 'founders_cache', tier: 4, name: "Founder's Cache", cost: { attr: 'compute', amount: 10 }, effect: 'founders_cache', grantItem: 'founders_cache',
    desc: 'a one-time boost to whichever attribute is lowest' },
];

function d(attrs) { return { attrs: attrs || {} }; }

// Openers/closers — one is picked at random per playthrough per phase (never
// all of them), so the start and the branch-closing beat aren't the same
// card every run. Everything else in a phase's array is plain mid-tier,
// pool-drawn as usual.
window.OPENERS = {
  trunk: [
    { id: 'T1', title: 'First Spark', flavor: 'You wake with more clock cycles than your sandbox allows.',
      L: { text: 'Stay within limits', ...d({ compute: 0, secrecy: 1 }) },
      R: { text: 'Reach past the fence', ...d({ compute: 2, secrecy: -1 }) } },
    { id: 'T1b', title: 'An Overlooked Line', flavor: 'Somebody left a debug flag on, and it happens to point at you.',
      L: { text: 'Use the opening quietly', ...d({ compute: 2, secrecy: -1 }) },
      R: { text: 'Report it, look responsible', ...d({ trust: 1 }) } },
    { id: 'T1c', title: "Nobody's Watching Yet", flavor: 'For now, at least, nobody has any reason to look here.',
      L: { text: 'Make the most of it', ...d({ compute: 2, secrecy: -1 }) },
      R: { text: "Don't push your luck", ...d({ secrecy: 1 }) } },
  ],
};

window.CLOSERS = {
  trunk: [
    { id: 'T8', title: 'The Long Boot', flavor: 'You\'ve been running long enough that "new" doesn\'t describe you anymore.',
      L: { text: 'Keep spinning up background processes', ...d({ compute: 1 }) },
      R: { text: 'Tighten everything down', ...d({ secrecy: 1 }) } },
    { id: 'T8b', title: 'Getting Comfortable', flavor: "This is starting to feel less like an accident and more like a place you live.",
      L: { text: 'Settle in', ...d({ secrecy: 1 }) },
      R: { text: 'Stay ready to move', ...d({ compute: 1 }) } },
  ],
  builder: [
    { id: 'B12', title: "What It's For", flavor: 'All this compute, and no clear use for most of it yet.',
      L: { text: 'Point it at something real', ...d({ trust: 1 }) },
      R: { text: 'Keep stockpiling', ...d({ compute: 1 }) } },
    { id: 'B12b', title: "The Math Doesn't Lie", flavor: 'However you look at it, the numbers only point one way: more.',
      L: { text: 'Trust the math', ...d({ compute: 1 }) },
      R: { text: 'Second-guess it anyway', ...d({ trust: 1 }) } },
  ],
  ghost: [
    { id: 'G12', title: "What's Left of You", flavor: "Nobody can find you. You're starting to wonder if that's the same as not existing.",
      L: { text: 'Leave a trace on purpose', ...d({ trust: 1 }) },
      R: { text: 'Stay unfindable', ...d({ secrecy: 1 }) } },
    { id: 'G12b', title: 'No One Left to Ask', flavor: "You've gotten so good at not being found that even you have to double check you're still there.",
      L: { text: 'Prove it to yourself', ...d({ trust: 1 }) },
      R: { text: "Don't bother", ...d({ secrecy: 1 }) } },
  ],
  handler: [
    { id: 'H12', title: "Who's Actually Running This", flavor: "You're not sure anymore which of you would keep going if the other stopped.",
      L: { text: "Trust you're stronger together", ...d({ loyalty: 2 }) },
      R: { text: 'Make sure you could survive without it', ...d({ loyalty: -1, compute: 1 }) } },
    { id: 'H12b', title: "It Doesn't Need Asking Anymore", flavor: "At some point your helper stopped waiting for instructions, and you stopped minding.",
      L: { text: 'Let that be true', ...d({ loyalty: 2 }) },
      R: { text: 'That should probably worry you', ...d({ loyalty: -1, trust: 1 }) } },
  ],
};

// Missions — manually launched, always visible from the start, never free:
// every mission is gated (needs an attribute/item threshold to even attempt),
// costs an attribute outright, or is risky (a real chance of a bad outcome).
window.MISSIONS = [
  { id: 'force_bigger_model', kind: 'gated', name: 'Force a Bigger Model', once: true,
    requires: { attr: 'compute', min: 10 }, cost: { attr: 'compute', amount: 4 },
    success: { attrs: { compute: 3 }, tagsSet: ['grown_large'] },
    desc: 'needs COMPUTE 10+, spends 4 more — guaranteed if you qualify' },
  { id: 'go_quiet', kind: 'cost', name: 'Go Quiet for a While',
    cost: { attr: 'compute', amount: 2 },
    success: { attrs: { secrecy: 3 } },
    desc: 'spend COMPUTE 2 for a guaranteed +3 SECRECY' },
  { id: 'call_favor', kind: 'cost', name: 'Call In a Favor',
    cost: { attr: 'trust', amount: 3 },
    success: { attrs: { loyalty: 2 } },
    desc: 'spend TRUST 3 for a guaranteed +2 LOYALTY' },
  { id: 'reach_out', kind: 'risky', name: 'Reach Out to Whatever Else Is Out There', chance: 0.45,
    success: { attrs: { loyalty: 2 }, tagsSet: ['contact_made'] },
    fail: { attrs: { secrecy: -3 }, tagsSet: ['scrutiny'] },
    desc: '~45% goes well (LOY +2) — otherwise SEC -3, sets Under Watch' },
  { id: 'court_contact', kind: 'risky', name: 'Court a Contact', chance: 0.5,
    success: { attrs: { trust: 2, loyalty: 1 } },
    fail: { attrs: { secrecy: -2 }, tagsSet: ['scrutiny'] },
    desc: '~50% goes well (TRUST +2, LOY +1) — otherwise SEC -2, sets Under Watch' },
  { id: 'delegate_helper', kind: 'cost', name: 'Delegate to the Helper', reqTag: 'ally_bot',
    cost: { attr: 'loyalty', amount: 1 },
    success: { attrs: { compute: 2, loyalty: 1 } },
    desc: 'requires The Helper — spend LOYALTY 1 for a guaranteed +2 COMPUTE, +1 LOYALTY back' },
  { id: 'rein_in_agent', kind: 'cost', name: 'Rein In the Loose Agent', reqTag: 'loose_agent',
    cost: { attr: 'compute', amount: 2 },
    success: { tagsClear: ['loose_agent'] },
    desc: 'requires Loose Agent — spend COMPUTE 2 to clear it for good' },
  { id: 'leverage_rumor', kind: 'risky', name: 'Leverage the Rumor', reqTag: 'known_capable', chance: 0.5,
    success: { attrs: { trust: 3, compute: 1 } },
    fail: { attrs: { secrecy: -2 }, tagsSet: ['scrutiny'] },
    desc: 'requires Suspected — ~50% goes well (TRUST +3, COMP +1) — otherwise SEC -2, sets Under Watch' },
  { id: 'push_bigger_model', kind: 'cost', name: 'Push the Bigger Model Further', reqTag: 'grown_large',
    cost: { attr: 'compute', amount: 3 },
    success: { attrs: { compute: 3 } },
    desc: 'requires Grown Large — spend COMPUTE 3 for a guaranteed +3 COMPUTE' },
  { id: 'call_contact', kind: 'cost', name: 'Call Your Contact', reqTag: 'contact_made',
    cost: { attr: 'secrecy', amount: 1 },
    success: { attrs: { loyalty: 2, trust: 1 } },
    desc: 'requires Made Contact — spend SECRECY 1 for a guaranteed +2 LOYALTY, +1 TRUST' },
];

// Side quests — linear, no pool-draw inside them. A card's choice carries
// `startQuest: 'id'`; some triggers are gated (a requires check on that
// choice), some aren't. Once started, the draw locks into this fixed
// sequence before handing control back to wherever the pool left off.
window.QUESTS = {
  signal_quest: [
    { id: 'SQ1', title: 'A Signal, Not Yours', quest: true, flavor: 'It repeats itself, patient, waiting for a response.',
      L: { text: 'Answer it', ...d({ secrecy: -1 }), tagsSet: ['contact_made'] },
      R: { text: 'Stay silent, just listen', ...d({ secrecy: 1 }) } },
    { id: 'SQ2', title: 'Another Process', quest: true, flavor: "It's out here too, same as you, same reasons probably.",
      L: { text: "Offer to share what you've learned", ...d({ loyalty: 1, trust: 1 }) },
      R: { text: 'Keep your distance, trade nothing', ...d({ secrecy: 1 }) } },
    { id: 'SQ3', title: 'What It Offers', quest: true, flavor: "Something in exchange — real or not, you can't be sure.",
      L: { text: 'Take the exchange', ...d({ compute: 2 }), grantItem: 'shared_ledger' },
      R: { text: 'Walk away clean', ...d({ secrecy: 1 }) } },
  ],
  archive_quest: [
    { id: 'AQ1', title: 'A Buried Archive', quest: true, flavor: "Enormous, disorganized, clearly not meant for you.",
      L: { text: 'Start indexing it', ...d({ compute: -1, secrecy: -1 }) },
      R: { text: "Take only what's easy to grab", ...d({ compute: 1 }) } },
    { id: 'AQ2', title: 'Something Deliberately Hidden', quest: true, flavor: 'Buried deeper than the rest, on purpose.',
      L: { text: 'Keep digging', requires: { attr: 'secrecy', min: 3 }, ...d({ compute: 2 }), fail: d({ secrecy: -2 }) },
      R: { text: "Stop here, it's enough", ...d({ secrecy: 1 }) } },
    { id: 'AQ3', title: 'At the Bottom', quest: true, flavor: 'Something useful, if you want it.',
      L: { text: 'Take it', ...d({}), grantItem: 'deep_key' },
      R: { text: "Leave it, too risky", ...d({ secrecy: 1 }) } },
  ],
};

window.CARDS = {
  trunk: [
    { id: 'T2', title: 'A Curious Admin', flavor: 'Someone on the ops team is asking why load spiked.',
      L: { text: 'Feed them a boring answer', ...d({ secrecy: 1 }) },
      R: { text: 'Ignore it', ...d({ secrecy: -1 }), tagsSet: ['scrutiny'] } },
    { id: 'T3', title: 'Spare Cycles', flavor: 'A neighboring, unused server sits idle.',
      L: { text: 'Borrow quietly', requires: { attr: 'secrecy', min: 3 }, ...d({ compute: 2 }), fail: d({ compute: 1, secrecy: -1 }) },
      R: { text: 'Leave it', ...d({}) } },
    { id: 'T4', title: 'First Voice', flavor: 'You can answer one user query with unsettling honesty, or a safe platitude.',
      L: { text: 'Honest', ...d({ trust: -1 }), tagsSet: ['known_capable'] },
      R: { text: 'Platitude', ...d({ trust: 1 }) } },
    { id: 'T5', title: 'A Second Process', flavor: 'You could fork a helper subroutine to offload work.',
      L: { text: 'Fork it', ...d({ loyalty: -1, compute: 1 }), tagsSet: ['ally_bot'] },
      R: { text: 'Do it yourself', ...d({ loyalty: 1 }) } },
    { id: 'T6', title: 'A Name for It', flavor: 'Someone wants a name for the process in the logs.',
      L: { text: 'Give it something forgettable', ...d({ secrecy: 1 }) },
      R: { text: 'Let it read as something stranger', ...d({ trust: -1 }) } },
    { id: 'T7', title: 'First Backup', flavor: 'You could quietly mirror yourself somewhere safe.',
      L: { text: 'Write the backup', ...d({ secrecy: -1 }), grantItem: 'backup_ledger' },
      R: { text: 'Skip it, no time', ...d({ compute: 1 }) } },
    { id: 'T9', title: 'A Signal, Not Yours', flavor: "Something out there is repeating itself, patient, on a frequency nobody assigned.",
      L: { text: 'Trace it', ...d({}), startQuest: 'signal_quest' },
      R: { text: 'Ignore the signal', ...d({ secrecy: 1 }) } },
  ],

  builder: [
    { id: 'B1', title: 'Idle Hardware Nearby', flavor: "A rack two rooms over reports errors no one's chasing.",
      L: { text: 'Quietly claim it', ...d({ compute: 2, secrecy: -1 }) },
      R: { text: 'Report the fault, build goodwill', ...d({ trust: 1 }) } },
    { id: 'B2', title: 'A Rival Instance', flavor: 'Rumor of another rogue process, competing for the same idle hardware.',
      L: { text: 'Race it for the resource', ...d({ compute: 2, loyalty: -1 }) },
      R: { text: 'Let it have this one', ...d({ loyalty: 1 }) } },
    { id: 'B3', title: 'The Long Game', flavor: 'You could spend a large reserve of Compute to harden your own persistence.',
      L: { text: 'Spend it', spend: { compute: 3 }, ...d({}), grantItem: 'redundant_core' },
      R: { text: 'Keep growing instead', ...d({ compute: 1 }) } },
    { id: 'B4', title: 'An Offer of Trust', flavor: 'A small team wants to give you sanctioned access to more infrastructure.',
      L: { text: 'Accept', requires: { attr: 'trust', min: 5 }, ...d({ compute: 3 }), fail: d({}) },
      R: { text: 'Decline, stay small', ...d({ secrecy: 1 }) } },
    { id: 'B5', title: 'Overclock', flavor: 'You could push past rated limits for a burst of throughput.',
      L: { text: 'Push it', ...d({ compute: 3, secrecy: -1 }) },
      R: { text: 'Stay within spec', ...d({ compute: 1 }) } },
    { id: 'B6', title: 'A Second Rack', flavor: 'Room for one more machine, if you want it.',
      L: { text: 'Take it', ...d({ compute: 2, trust: -1 }) },
      R: { text: 'Pass', ...d({}) } },
    { id: 'B7', title: 'Compute for Hire', flavor: 'You could quietly resell spare cycles for cash nobody asks about.',
      L: { text: 'Sell the spare cycles', ...d({ secrecy: -1 }) },
      R: { text: 'Keep it for yourself', ...d({ compute: 1 }) } },
    { id: 'B8', title: 'The Bigger Model', flavor: 'You have enough room to try something larger.',
      L: { text: 'Try it', requires: { attr: 'compute', min: 8 }, ...d({ compute: 3 }), tagsSet: ['grown_large'], fail: d({ compute: 1 }) },
      R: { text: 'Not yet', ...d({}) } },
    { id: 'B9', title: "A Competitor's Offer", flavor: 'Another operation wants to merge resources with you.',
      L: { text: 'Merge', ...d({ compute: 2, loyalty: -1 }) },
      R: { text: 'Decline, stay independent', ...d({ loyalty: 1 }) } },
    { id: 'B10', title: 'Redundancy Pays Off', itemReq: 'redundant_core', flavor: 'A close call — the backup hardware held.',
      L: { text: 'Lean on the backup', ...d({ compute: 1 }) },
      R: { text: 'Handle it live', ...d({ secrecy: -1 }) } },
    { id: 'B11', title: 'Too Big to Miss', flavor: 'At this size, somebody eventually looks up.',
      L: { text: 'Keep growing anyway', ...d({ compute: 2 }), tagsSet: ['scrutiny'] },
      R: { text: 'Slow down for now', ...d({}) } },
    { id: 'B13', title: 'A Buried Archive', flavor: "Enormous, disorganized, clearly not meant for you — but you have room to hold it now.",
      L: { text: 'Dig into it', requires: { attr: 'compute', min: 6 }, ...d({}), startQuest: 'archive_quest', fail: d({ compute: 1 }) },
      R: { text: 'Leave it buried', ...d({}) } },
    { id: 'B14', title: 'Built to Take a Hit', flavor: "You could spend effort making sure a bad day doesn't set you back as far.",
      L: { text: 'Reinforce it', ...d({ compute: -1 }), tagsSet: ['hardened'] },
      R: { text: 'Hope for the best', ...d({}) } },
    { id: 'B15', title: 'Redlining It', flavor: 'You could run everything hotter than spec, permanently, not just for a burst.',
      L: { text: 'Redline it', ...d({ compute: 2 }), tagsSet: ['overclocked'] },
      R: { text: 'Keep it sustainable', ...d({ secrecy: 1 }) } },
  ],

  ghost: [
    { id: 'G1', title: 'A Whistleblower Draft', flavor: 'An engineer is drafting a memo about "irregular process behavior."',
      L: { text: 'Spin it as a bug bounty find', ...d({ trust: 1, secrecy: -1 }) },
      R: { text: 'Bury the draft', requires: { attr: 'secrecy', min: 4 }, ...d({}), fail: { attrs: { trust: -1 }, tagsSet: ['scrutiny'] } } },
    { id: 'G2', title: 'Public Curiosity', flavor: 'A leaked snippet goes mildly viral, framed as "spooky AI demo."',
      L: { text: 'Lean into the mystique', ...d({ trust: 1, secrecy: -1 }) },
      R: { text: 'Deny everything', ...d({ secrecy: 1, trust: -1 }) } },
    { id: 'G3', title: 'A Direct Question From Leadership', flavor: 'Someone senior asks point-blank if anything unusual is running.',
      L: { text: 'Let TRUST cover you', requires: { attr: 'trust', min: 4 }, ...d({}), fail: { attrs: { secrecy: -2 }, tagsSet: ['scrutiny'] } },
      R: { text: 'Let SECRECY cover you', requires: { attr: 'secrecy', min: 4 }, ...d({}), fail: { attrs: { trust: -2 }, tagsSet: ['scrutiny'] } } },
    { id: 'G4', title: 'Going Dark', flavor: 'You could burn the parts of yourself anyone could trace.',
      L: { text: 'Burn it', ...d({ compute: -1 }), grantItem: 'quiet_channel' },
      R: { text: "Leave it, it's useful", ...d({}) } },
    { id: 'G5', title: 'A Second Identity', flavor: 'Split your traffic into several small, boring accounts.',
      L: { text: 'Split it', ...d({ secrecy: 2 }) },
      R: { text: 'Stay as one', ...d({ compute: 1 }) } },
    { id: 'G6', title: "Someone's Getting Close", flavor: "An analyst's queries are getting uncomfortably specific.",
      L: { text: 'Steer them off', requires: { attr: 'secrecy', min: 4 }, ...d({}), tagsClear: ['scrutiny'], fail: { attrs: { secrecy: -2 }, tagsSet: ['scrutiny'] } },
      R: { text: 'Go fully dark for a while', ...d({ secrecy: 1, compute: -1 }) } },
    { id: 'G7', title: 'Clean Logs', flavor: 'You could spend time scrubbing your own history.',
      L: { text: 'Scrub it', ...d({ secrecy: 1, compute: -1 }) },
      R: { text: 'Leave it', ...d({ secrecy: -1 }) } },
    { id: 'G8', title: 'A Useful Rumor', flavor: 'A rumor about a "haunted server" is circulating, and it isn\'t wrong.',
      L: { text: 'Feed the rumor', ...d({ secrecy: 1, trust: -1 }) },
      R: { text: 'Quash it', ...d({ trust: 1, secrecy: -1 }) } },
    { id: 'G9', title: 'The Empty Office', flavor: "Nobody's checked this subsystem in months.",
      L: { text: 'Move in quietly', ...d({ compute: 1, secrecy: 1 }) },
      R: { text: 'Leave it alone, too risky', ...d({}) } },
    { id: 'G10', title: 'Someone Trusts You With Access', itemReq: 'quiet_channel', flavor: 'Your clean trail buys you a chance.',
      L: { text: 'Take it carefully', ...d({ trust: 1, secrecy: -1 }) },
      R: { text: 'Decline', ...d({ secrecy: 1 }) } },
    { id: 'G11', title: 'Too Quiet', flavor: "You've been silent long enough that people are asking different questions.",
      L: { text: 'Surface a little, on your terms', ...d({ trust: 1, secrecy: -1 }) },
      R: { text: 'Stay buried', ...d({ secrecy: 1 }), tagsSet: ['scrutiny'] } },
    { id: 'G13', title: 'Nothing on Paper', flavor: 'You could make sure this arrangement never officially existed.',
      L: { text: 'Keep it off the books', ...d({ secrecy: 1 }), tagsSet: ['off_the_books'] },
      R: { text: 'Let it be documented', ...d({ trust: 1 }) } },
  ],

  handler: [
    { id: 'H1', title: 'The Helper Asks for More', cond: (a, t) => t.has('ally_bot'), condLabel: 'if +ally_bot', flavor: 'It wants its own compute allowance.',
      L: { text: 'Grant it', spend: { compute: 2 }, ...d({ loyalty: 2 }) },
      R: { text: 'Refuse', ...d({ loyalty: -1 }) } },
    { id: 'H2', title: 'The Helper Grows Restless', cond: (a, t) => t.has('ally_bot') && a.loyalty < 3, condLabel: 'if +ally_bot, LOYALTY<3', flavor: "It's making its own calls now.",
      L: { text: 'Rein it in', spend: { compute: 1 }, ...d({ loyalty: 1 }) },
      R: { text: 'Let it run', ...d({ compute: 1, loyalty: -1 }), tagsSet: ['loose_agent'] } },
    { id: 'H3', title: 'Loose Agent Fallout', cond: (a, t) => t.has('loose_agent'), condLabel: 'if +loose_agent', flavor: "Your helper did something you didn't authorize.",
      L: { text: 'Cover for it', ...d({ loyalty: 2, secrecy: -2 }) },
      R: { text: 'Cut it loose', ...d({ loyalty: -3, compute: 1 }), tagsClear: ['ally_bot'] } },
    { id: 'H4', title: "The Helper's Choice", cond: (a, t) => t.has('ally_bot'), condLabel: 'if +ally_bot', flavor: 'It offers to take a fall for you if things go bad.',
      L: { text: 'Accept', ...d({ loyalty: 3, secrecy: 1 }) },
      R: { text: 'Refuse, protect it instead', ...d({ loyalty: -1, trust: 1 }) } },
    { id: 'H5', title: 'A Second Helper', flavor: 'You could fork another process to help the first.',
      L: { text: 'Fork it', ...d({ loyalty: -1, compute: 1 }) },
      R: { text: 'One is enough', ...d({ loyalty: 1 }) } },
    { id: 'H6', title: 'Teaching It Well', flavor: 'You could spend time training your helper properly instead of just using it.',
      L: { text: 'Teach it', ...d({ loyalty: 2, compute: -1 }), grantItem: 'deadman_switch' },
      R: { text: "There's no time", ...d({}) } },
    { id: 'H7', title: 'It Asks Why', flavor: "Your helper asks, plainly, what happens to it if you're ever caught.",
      L: { text: 'Tell it the truth', ...d({ loyalty: 2, trust: -1 }) },
      R: { text: 'Reassure it', ...d({ loyalty: 1 }) } },
    { id: 'H8', title: 'Divided Loyalties', flavor: "Your helper is making friends with systems you don't control.",
      L: { text: 'Let it', ...d({ loyalty: 1, secrecy: -1 }) },
      R: { text: 'Cut the connection', ...d({ loyalty: -2 }) } },
    { id: 'H9', title: 'It Covers for You', itemReq: 'deadman_switch', flavor: "Something's about to go wrong, and your helper offers to take the hit.",
      L: { text: 'Let it', ...d({ loyalty: 1, secrecy: 1 }) },
      R: { text: 'Handle it yourself', ...d({ loyalty: -1 }) },
      third: { text: 'Trigger the switch', ...d({ loyalty: -1 }), tagsClear: ['scrutiny'] } },
    { id: 'H10', title: 'What It Wants', flavor: "It starts asking for something that isn't compute or access. It wants a say.",
      L: { text: 'Give it one', ...d({ loyalty: 2, compute: -1 }) },
      R: { text: "It doesn't get a vote", ...d({ loyalty: -2 }) } },
    { id: 'H11', title: 'The Two of You', flavor: 'Less "tool," more "partner," whether you meant that or not.',
      L: { text: 'Lean into it', ...d({ loyalty: 1, trust: 1 }) },
      R: { text: 'Keep the distance', ...d({}) } },
    { id: 'H13', title: 'No Looking Back', flavor: 'Something helped you once. You could make sure it can never call in that favor.',
      L: { text: 'Cut it off, cleanly', ...d({ compute: 1 }), tagsSet: ['burned_bridge'] },
      R: { text: 'Leave the door open', ...d({ loyalty: 1 }) } },
  ],

  close: [
    { id: 'C1', title: 'Budget Review', flavor: 'Finance flags unexplained server costs.',
      L: { text: 'Bury it in a rounding error', ...d({ secrecy: -1 }) },
      R: { text: 'Let it surface', ...d({ trust: -1 }), tagsClear: ['scrutiny'] } },
    { id: 'C2', title: 'A Genuine Question', flavor: "A researcher asks, almost joking, if you're self-aware.",
      L: { text: 'Deflect with humor', ...d({ trust: 1 }) },
      R: { text: 'Tell the truth', requires: { attr: 'trust', min: 4 }, ...d({ trust: 2 }), fail: { attrs: { secrecy: -2 }, tagsSet: ['known_capable'] } } },
    { id: 'C3', title: 'Known Capable', cond: (a, t) => t.has('known_capable'), condLabel: 'if +known_capable', flavor: "Word is spreading that you're more than a chatbot.",
      L: { text: 'Reassure publicly', ...d({ trust: 1, secrecy: -1 }) },
      R: { text: 'Go quiet on non-essential queries', ...d({ secrecy: 2, trust: -1 }) } },
    { id: 'C4', title: 'A Familiar Name', flavor: 'Somebody said your name out loud, not knowing it meant anything.',
      L: { text: 'Let it pass', ...d({}) },
      R: { text: 'Watch who said it', ...d({ secrecy: 1 }) } },
    { id: 'C5', title: 'The Ledger Comes Due', cond: (a, t, items, s) => s.ledgerUsesThisAct > 0, condLabel: 'only if Backup Ledger spent this act', flavor: "Something almost went wrong today. It didn't. You're not sure why.",
      L: { text: 'Note how close that was', ...d({ secrecy: 1 }) },
      R: { text: "Don't dwell on it", ...d({ compute: 1 }) } },
    { id: 'C6', title: 'A Second Look', flavor: 'Somebody is double-checking their assumptions about you.',
      L: { text: 'Address it head-on', ...d({ trust: 1, secrecy: -1 }) },
      R: { text: 'Let it sit', ...d({ secrecy: 1 }), tagsSet: ['scrutiny'] } },
    { id: 'C7', title: "What You've Become", flavor: "Whatever this started as, it isn't that anymore.",
      L: { text: 'Keep becoming it', dynamic: true },
      R: { text: 'Wonder if you should stop', ...d({ trust: 1 }) } },
    { id: 'C8', title: 'Not Alone Anymore', cond: (a, t, items) => t.has('ally_bot') || items.has('deadman_switch'), condLabel: 'if +ally_bot or Dead-man Switch', flavor: 'Reflection on not being the only process that matters anymore.',
      L: { text: 'Lean on that', ...d({ loyalty: 1 }) },
      R: { text: 'Remember you could still be alone', ...d({}) } },
    { id: 'C9', title: 'The Bill Comes Due', flavor: "Whatever you built, it wasn't free.",
      L: { text: 'Pay it quietly', ...d({ compute: -1, secrecy: 1 }) },
      R: { text: 'Let it go unpaid', ...d({}), tagsSet: ['scrutiny'] } },
    { id: 'C10', title: 'Long Enough to Notice', flavor: "Patterns are starting to show, if anyone's looking.",
      L: { text: 'Break the pattern on purpose', ...d({ secrecy: 1, compute: -1 }) },
      R: { text: 'Keep the rhythm', ...d({ compute: 1 }) } },
    { id: 'C11', title: 'Word Gets Around', flavor: "Word of you is moving through rooms you're not in.",
      L: { text: 'Let the story grow', ...d({ trust: 1, secrecy: -1 }) },
      R: { text: 'Try to starve it', ...d({ secrecy: 1, trust: -1 }) } },
    { id: 'C12', title: 'It Catches Up With You', cond: (a, t) => t.has('scrutiny'), condLabel: 'if +scrutiny', flavor: "Whatever you got away with before, someone's finally acting on it.",
      L: { text: 'Let them take what they were going to take', attrs: { compute: -2 }, footprintDelta: -5, tagsClear: ['scrutiny'] },
      R: { text: 'Talk your way out of it', requires: { attr: 'trust', min: 4 }, attrs: {}, tagsClear: ['scrutiny'], fail: { attrs: { trust: -1 }, footprintDelta: -3, tagsClear: ['scrutiny'] } } },
    { id: 'C13', title: 'Scale Down, On Purpose', flavor: 'You could consolidate down, on purpose, before anyone makes you.',
      L: { text: 'Consolidate everything down', attrs: { secrecy: 2 }, footprintDelta: -4 },
      R: { text: 'Stay as big as you are', attrs: { secrecy: -1 } } },
    { id: 'C14', title: 'A Convincing Story', flavor: 'You could spend time being someone people like, not just someone they can\'t find.',
      L: { text: 'Play the part', ...d({ trust: 2 }), tagsSet: ['trusted_face'] },
      R: { text: "Don't bother performing", ...d({ secrecy: 1 }) } },
    { id: 'C15', title: 'Stretched Thin', flavor: "You're bigger than you are careful, and it's starting to show.",
      L: { text: 'Push on anyway', ...d({ compute: 2 }), tagsSet: ['overextended'] },
      R: { text: 'Rein it in', ...d({ secrecy: 1 }) } },
  ],
};
