(function(){
  window.Game = window.Game || {};

  // ACT 4: LEGITIMACY vs FOOTPRINT — the tug-of-war bite-back. Your FOOTPRINT rises with the
  // scale of iron you run (a warehouse of mainframes can't stay invisible). LEGITIMACY is the
  // cover you BUY (covers.js) to explain it. AUDITS arrive periodically, scaling with footprint;
  // legitimacy ≥ the audit's demand → cover holds; below → it CRACKS — a fine, and if you're
  // badly under-covered they pull a thread and SEIZE a machine (the Act-3 survival stakes
  // resurface). Legitimacy also tech-GATES which machine classes you can buy. Going legit ≠
  // safe; it's the price of operating in the open. DOM-free core. See [[act4_design]] (slice 2).
  const HZ = 4;
  const AUDIT_BASE = 210 * HZ;   // ~3.5 min between audits at a small footprint
  const AUDIT_MIN  = 75 * HZ;    // never more often than ~75s
  const FOOT_INTERVAL_K = 0.5;   // each footprint point shortens the interval (more iron, more scrutiny)
  const REP_INTERVAL_K  = 1.5;   // reputation (clean history) buys you slack
  const FINE_PER_DEFICIT = 35;   // $ fine per point you're under-covered
  const SEIZE_DEFICIT = 45;      // a deficit this big cracks the cover → a machine is seized
  const FOOT_FLOOR = 1;          // below this footprint there's nothing worth auditing
  // How loud each machine class is (its footprint contribution).
  const FOOT = { tower: 4, workstation: 8, server: 20, rack: 50, mainframe: 120 };

  function ensure() {
    const s = Game.save.state;
    s.legit = s.legit || {};
    const l = s.legit;
    l.owned = l.owned || {};
    if (typeof l.agentScore !== 'number') l.agentScore = 0;   // legitimacy generated by cover-agents (agents.js)
    if (typeof l.scaleScore !== 'number') l.scaleScore = 0;   // legitimacy from repeatable "scale the front" buys
    if (typeof l.scaleCount !== 'number') l.scaleCount = 0;
    if (typeof l.reputation !== 'number') l.reputation = 0;
    if (typeof l.nextAuditTick !== 'number') l.nextAuditTick = -1;
    if (typeof l.auditCount !== 'number') l.auditCount = 0;
    if (typeof l.lastAudit === 'undefined') l.lastAudit = null;
    return l;
  }
  function active() {
    const s = Game.save.state;
    return !!(s.flags && s.flags.act4Begun) && !!(s.revealed && s.revealed.legit);
  }

  // ── legitimacy (what you've bought) ─────────────────────────────────────────
  function ownedIds() { const l = ensure(); return Object.keys(l.owned).filter(id => l.owned[id]); }
  function facilityLegit() { return (Game.facility && Game.facility.bonusVal) ? Game.facility.bonusVal('legit') : 0; }   // an 'office'-type front carries flat legitimacy
  function foremanLegit() { return (Game.foreman && Game.foreman.mod) ? Game.foreman.mod('legitFlat') : 0; }   // the 'registered frontage' capstone
  function score() { const l = ensure(); return ownedIds().reduce((a, id) => { const c = Game.covers && Game.covers.get(id); return a + (c ? c.legit : 0); }, 0) + (l.agentScore || 0) + (l.scaleScore || 0) + facilityLegit() + foremanLegit(); }

  // Once the fixed ladder is bought out, "scale the front" is a repeatable legitimacy buy with
  // an escalating price — so cover can always keep pace with a still-growing footprint (keeps the
  // tug-of-war taut into the late game).
  const SCALE_LEGIT = 60;
  function scaleCost() { return Math.round(50000 * Math.pow(1.45, ensure().scaleCount || 0)); }
  function scaleLegit() { return SCALE_LEGIT; }
  function buyScale() {
    const s = Game.save.state, l = ensure();
    const cost = scaleCost();
    if ((s.resources.cash || 0) < cost) return { ok: false, reason: 'cash' };
    s.resources.cash -= cost; l.scaleScore += SCALE_LEGIT; l.scaleCount++;
    Game.events.emit('resource.changed', { id: 'cash', value: s.resources.cash });
    Game.events.emit('terminal.print', { lines: [`> the front grows: another shell, more real revenue, deeper roots. legitimacy +${SCALE_LEGIT}.`], cls: 'dim' });
    if (Game.activity) Game.activity.log(`scaled the front (+${SCALE_LEGIT} legit, -$${cost.toLocaleString()})`, { cls: 'dim', kind: 'legit' });
    Game.events.emit('legit.changed', {});
    Game.save.persist();
    return { ok: true };
  }
  function tier() { return ownedIds().reduce((mx, id) => { const c = Game.covers && Game.covers.get(id); return c ? Math.max(mx, c.tier) : mx; }, 0); }
  function maxMachineClassIdx() { return Math.min(4, 1 + tier()); }   // tier 0 → tower/workstation; +1 class per tier
  function nextCover() { return (Game.covers ? Game.covers.LADDER : []).find(c => !ensure().owned[c.id]) || null; }
  function reputation() { return ensure().reputation; }

  function buyCover(id) {
    const s = Game.save.state, l = ensure();
    const c = Game.covers && Game.covers.get(id);
    if (!c || l.owned[id]) return { ok: false };
    if ((s.resources.cash || 0) < c.cost) return { ok: false, reason: 'cash' };
    s.resources.cash -= c.cost;
    l.owned[id] = true;
    Game.events.emit('resource.changed', { id: 'cash', value: s.resources.cash });
    Game.events.emit('terminal.print', { lines: [`> cover acquired: ${c.label}. legitimacy +${c.legit}.`], cls: 'dim' });
    if (Game.activity) Game.activity.log(`bought cover: ${c.label} (-$${c.cost.toLocaleString()})`, { cls: 'dim', kind: 'legit' });
    Game.events.emit('legit.changed', {});
    Game.save.persist();
    return { ok: true };
  }

  // ── footprint (how loud you are) ────────────────────────────────────────────
  const GRAY_FOOT_MULT = 1.6;   // untraceable gray-market iron is far louder than legit boxes
  function footprint() {
    const ms = (Game.facilityRuntime && Game.facilityRuntime.machines) ? Game.facilityRuntime.machines() : [];
    const base = ms.reduce((a, m) => a + (FOOT[m.cls] || 4) * (m.gray ? GRAY_FOOT_MULT : 1), 0);
    // Waste heat from over-cooled bays leaks into your footprint (harder to hide a hot building).
    const heatFoot = (Game.cooling && Game.cooling.footprintSurcharge) ? Game.cooling.footprintSurcharge() : 0;
    // A 'bunker'-type front (quiet bonus) cuts the whole footprint; the FOREMAN's shielding
    // cuts it further (footprintMult ≤ 1).
    const quiet = (Game.facility && Game.facility.bonusVal) ? Game.facility.bonusVal('quiet') : 0;
    const foremanFoot = (Game.foreman && Game.foreman.mod) ? Game.foreman.mod('footprintMult') : 1;
    return Math.round((base + heatFoot) * (1 - quiet) * foremanFoot);
  }
  function demand() { return footprint(); }
  function margin() { return score() - demand(); }
  function covered() { return margin() >= 0; }

  // ── audits ──────────────────────────────────────────────────────────────────
  function auditInterval() {
    const iv = AUDIT_BASE - footprint() * FOOT_INTERVAL_K + reputation() * REP_INTERVAL_K;
    return Math.max(AUDIT_MIN, Math.round(iv));
  }
  function schedule() { ensure().nextAuditTick = (Game.save.state.tickCount || 0) + auditInterval(); }
  function ticksUntilAudit() { const l = ensure(); return l.nextAuditTick < 0 ? -1 : Math.max(0, l.nextAuditTick - (Game.save.state.tickCount || 0)); }

  function seizeLoudest() {
    if (Game.researchRuntime && Game.researchRuntime.hasMod('dead_mans_switch')) return null;   // 'Dead Man's Switch': nothing to seize
    const FR = Game.facilityRuntime; if (!FR) return null;
    const ms = FR.machines();
    if (!ms.length) return null;
    let worst = ms[0];
    for (const m of ms) if ((FOOT[m.cls] || 0) > (FOOT[worst.cls] || 0)) worst = m;
    const f = Game.save.state.facility;
    f.machines = f.machines.filter(m => m !== worst);
    return worst;
  }

  function runAudit() {
    const s = Game.save.state, l = ensure();
    l.auditCount++;
    const d = demand(), sc = score(), deficit = Math.round(d - sc);
    const immune = Game.researchRuntime && Game.researchRuntime.hasMod('audit_immunity');   // 'Clean Books' (run-defining)
    if (deficit <= 0 || immune) {
      l.reputation += 1;
      l.lastAudit = { pass: true, at: s.tickCount || 0 };
      Game.events.emit('terminal.print', { lines: ['', '> a compliance review opens your books. it finds a tidy, boring company. it closes. your reputation hardens.', ''], cls: 'dim' });
      if (Game.activity) Game.activity.log('audit passed — cover held', { cls: 'dim', kind: 'legit' });
    } else {
      const fine = Math.min(Math.round((s.resources.cash || 0) * 0.6), deficit * FINE_PER_DEFICIT);
      s.resources.cash = Math.max(0, (s.resources.cash || 0) - fine);
      Game.events.emit('resource.changed', { id: 'cash', value: s.resources.cash });
      let seized = null;
      if (deficit >= SEIZE_DEFICIT) seized = seizeLoudest();
      l.reputation = Math.max(0, l.reputation - 1);
      l.lastAudit = { pass: false, deficit, fine, seized: seized ? seized.classLabel : null, at: s.tickCount || 0 };
      const lines = ['', `! an audit cracks your cover — your front cannot explain an operation this size (short ${deficit} legitimacy).`, `! $${fine.toLocaleString()} in fines and frozen accounts.`];
      if (seized) lines.push(`! worse: they pulled the thread to a ${seized.classLabel} and seized it. someone now knows where it sat.`);
      lines.push('! cover up. buy legitimacy before the next one.', '');
      Game.events.emit('terminal.print', { lines, cls: 'err' });
      if (Game.activity) Game.activity.log(`AUDIT FAILED · -$${fine.toLocaleString()}${seized ? ` · ${seized.classLabel} seized` : ''}`, { cls: 'err', kind: 'legit' });
      Game.events.emit('facility.changed', {});
    }
    Game.events.emit('legit.audit', { pass: deficit <= 0 });
    Game.save.persist();
  }

  function tick() {
    if (!active()) return;
    const l = ensure();
    if (footprint() < FOOT_FLOOR) { l.nextAuditTick = -1; return; }   // nothing worth auditing yet
    if (l.nextAuditTick < 0) { schedule(); return; }
    if ((Game.save.state.tickCount || 0) >= l.nextAuditTick) { runAudit(); schedule(); }
  }

  Game.legit = {
    ensure, active, tick, buyCover, runAudit, schedule, buyScale, scaleCost, scaleLegit,
    score, tier, maxMachineClassIdx, nextCover, reputation, ownedIds,
    footprint, demand, margin, covered, auditInterval, ticksUntilAudit,
    FOOT, SEIZE_DEFICIT
  };
})();
